// GENERATED by scripts/gen-stories.mjs from the app's series files.
// Do not edit by hand: run `npm run gen:stories` instead.

import type { Series } from '@/data/types';

export const allSeries: Series[] = [
  {
    "id": "adam_en",
    "title": "Hazrat Adam (A.S.)",
    "description": "A 6-part story about the beginning of humanity.",
    "language": "english",
    "category": "prophets",
    "cover": "adam",
    "episodes": [
      {
        "id": "adam_en_01",
        "title": "Ep 1 · Before the First Footstep",
        "audioKey": "en/adam/01_before_the_first_footstep.ogg",
        "durationMs": 446728,
        "previewEndMs": 224160
      },
      {
        "id": "adam_en_02",
        "title": "Ep 2 · The Secret of Knowledge",
        "audioKey": "en/adam/02_the_secret_of_knowledge.ogg",
        "durationMs": 380032,
        "previewEndMs": null
      },
      {
        "id": "adam_en_03",
        "title": "Ep 3 · I Am Better",
        "audioKey": "en/adam/03_i_am_better.ogg",
        "durationMs": 330722,
        "previewEndMs": null
      },
      {
        "id": "adam_en_04",
        "title": "Ep 4 · The Forbidden Tree",
        "audioKey": "en/adam/04_the_forbidden_tree.ogg",
        "durationMs": 337131,
        "previewEndMs": null
      },
      {
        "id": "adam_en_05",
        "title": "Ep 5 · The Door Was Still Open",
        "audioKey": "en/adam/05_the_door_was_still_open.ogg",
        "durationMs": 362556,
        "previewEndMs": null
      },
      {
        "id": "adam_en_06",
        "title": "Ep 6 · The Fire Called Envy",
        "audioKey": "en/adam/06_the_fire_called_envy.ogg",
        "durationMs": 517145,
        "previewEndMs": null
      }
    ]
  },
  {
    "id": "hud_en",
    "title": "Hazrat Hud (A.S.)",
    "description": "A 5-part story about pride, strength and humility.",
    "language": "english",
    "category": "prophets",
    "cover": "hud",
    "episodes": [
      {
        "id": "hud_en_01",
        "title": "Ep 1 · Nobody Can Beat Us",
        "audioKey": "en/hud/01_nobody_can_beat_us.ogg",
        "durationMs": 749032,
        "previewEndMs": 377231
      },
      {
        "id": "hud_en_02",
        "title": "Ep 2 · Look What We Built",
        "audioKey": "en/hud/02_look_what_we_built.ogg",
        "durationMs": 765817,
        "previewEndMs": null
      },
      {
        "id": "hud_en_03",
        "title": "Ep 3 · Who Gave You All This?",
        "audioKey": "en/hud/03_who_gave_you_all_this.ogg",
        "durationMs": 687858,
        "previewEndMs": null
      },
      {
        "id": "hud_en_04",
        "title": "Ep 4 · Strong Enough to Be Kind",
        "audioKey": "en/hud/04_strong_enough_to_be_kind.ogg",
        "durationMs": 761350,
        "previewEndMs": null
      },
      {
        "id": "hud_en_05",
        "title": "Ep 5 · When Strength Was Not Enough",
        "audioKey": "en/hud/05_when_strength_was_not_enough.ogg",
        "durationMs": 775997,
        "previewEndMs": null
      }
    ]
  },
  {
    "id": "idris_en",
    "title": "Hazrat Idris (A.S.)",
    "description": "A 3-part story about standing up for the truth.",
    "language": "english",
    "category": "prophets",
    "cover": "idris",
    "episodes": [
      {
        "id": "idris_en_01",
        "title": "Ep 1 · The Price of Standing for the Truth",
        "audioKey": "en/idris/01_the_price_of_standing_for_the_truth.ogg",
        "durationMs": 836232,
        "previewEndMs": 420987
      },
      {
        "id": "idris_en_02",
        "title": "Ep 2 · When Truth Becomes Heavy",
        "audioKey": "en/idris/02_when_truth_becomes_heavy.ogg",
        "durationMs": 926578,
        "previewEndMs": null
      },
      {
        "id": "idris_en_03",
        "title": "Ep 3 · The High Station",
        "audioKey": "en/idris/03_the_high_station.ogg",
        "durationMs": 933442,
        "previewEndMs": null
      }
    ]
  },
  {
    "id": "nuh_en",
    "title": "Hazrat Nuh (A.S.)",
    "description": "A 6-part story about patience and never giving up on good.",
    "language": "english",
    "category": "prophets",
    "cover": "nuh",
    "episodes": [
      {
        "id": "nuh_en_01",
        "title": "Ep 1 · What Was the Point?",
        "audioKey": "en/nuh/01_what_was_the_point.ogg",
        "durationMs": 766960,
        "previewEndMs": 386749
      },
      {
        "id": "nuh_en_02",
        "title": "Ep 2 · Try Again, Differently",
        "audioKey": "en/nuh/02_try_again_differently.ogg",
        "durationMs": 709002,
        "previewEndMs": null
      },
      {
        "id": "nuh_en_03",
        "title": "Ep 3 · When People Laugh",
        "audioKey": "en/nuh/03_when_people_laugh.ogg",
        "durationMs": 1003611,
        "previewEndMs": null
      },
      {
        "id": "nuh_en_04",
        "title": "Ep 4 · Only a Few",
        "audioKey": "en/nuh/04_only_a_few.ogg",
        "durationMs": 947791,
        "previewEndMs": null
      },
      {
        "id": "nuh_en_05",
        "title": "Ep 5 · Build Before They Understand",
        "audioKey": "en/nuh/05_build_before_they_understand.ogg",
        "durationMs": 1152020,
        "previewEndMs": null
      },
      {
        "id": "nuh_en_06",
        "title": "Ep 6 · What Remains",
        "audioKey": "en/nuh/06_what_remains.ogg",
        "durationMs": 1257743,
        "previewEndMs": null
      }
    ]
  },
  {
    "id": "salih_en",
    "title": "Hazrat Salih (A.S.)",
    "description": "A 5-part story about boundaries, rights and responsibility.",
    "language": "english",
    "category": "prophets",
    "cover": "salih",
    "episodes": [
      {
        "id": "salih_en_01",
        "title": "Ep 1 · Why Is Everything a Rule?",
        "audioKey": "en/salih/01_why_is_everything_a_rule.ogg",
        "durationMs": 669176,
        "previewEndMs": 347707
      },
      {
        "id": "salih_en_02",
        "title": "Ep 2 · But Tell Me Why",
        "audioKey": "en/salih/02_but_tell_me_why.ogg",
        "durationMs": 616899,
        "previewEndMs": null
      },
      {
        "id": "salih_en_03",
        "title": "Ep 3 · That Was My Turn",
        "audioKey": "en/salih/03_that_was_my_turn.ogg",
        "durationMs": 662665,
        "previewEndMs": null
      },
      {
        "id": "salih_en_04",
        "title": "Ep 4 · Ammi Will Never Know",
        "audioKey": "en/salih/04_ammi_will_never_know.ogg",
        "durationMs": 685499,
        "previewEndMs": null
      },
      {
        "id": "salih_en_05",
        "title": "Ep 5 · The Rule Was Not the Enemy",
        "audioKey": "en/salih/05_the_rule_was_not_the_enemy.ogg",
        "durationMs": 720367,
        "previewEndMs": null
      }
    ]
  },
  {
    "id": "fairness_en",
    "title": "The Golden Balance",
    "description": "A 10-part story about fairness.",
    "language": "english",
    "category": "moral",
    "cover": "fairness",
    "episodes": [
      {
        "id": "fairness_en_01",
        "title": "Ep 1 · The Golden Balance",
        "audioKey": "en/fairness/01_the_golden_balance.ogg",
        "durationMs": 359210,
        "previewEndMs": 180664
      },
      {
        "id": "fairness_en_02",
        "title": "Ep 2 · A Shadow in the Photograph",
        "audioKey": "en/fairness/02_a_shadow_in_the_photograph.ogg",
        "durationMs": 283798,
        "previewEndMs": null
      },
      {
        "id": "fairness_en_03",
        "title": "Ep 3 · The Bronze Key",
        "audioKey": "en/fairness/03_the_bronze_key.ogg",
        "durationMs": 286081,
        "previewEndMs": null
      },
      {
        "id": "fairness_en_04",
        "title": "Ep 4 · The Garden of Balance",
        "audioKey": "en/fairness/04_the_garden_of_balance.ogg",
        "durationMs": 283709,
        "previewEndMs": null
      },
      {
        "id": "fairness_en_05",
        "title": "Ep 5 · The Fair Path",
        "audioKey": "en/fairness/05_the_fair_path.ogg",
        "durationMs": 301609,
        "previewEndMs": null
      },
      {
        "id": "fairness_en_06",
        "title": "Ep 6 · The Missing Balance",
        "audioKey": "en/fairness/06_the_missing_balance.ogg",
        "durationMs": 309573,
        "previewEndMs": null
      },
      {
        "id": "fairness_en_07",
        "title": "Ep 7 · The Number Seventeen",
        "audioKey": "en/fairness/07_the_number_seventeen.ogg",
        "durationMs": 278731,
        "previewEndMs": null
      },
      {
        "id": "fairness_en_08",
        "title": "Ep 8 · The Hidden Passage",
        "audioKey": "en/fairness/08_the_hidden_passage.ogg",
        "durationMs": 360499,
        "previewEndMs": null
      },
      {
        "id": "fairness_en_09",
        "title": "Ep 9 · The Record of Contestant Seventeen",
        "audioKey": "en/fairness/09_the_record_of_contestant_seventeen.ogg",
        "durationMs": 358163,
        "previewEndMs": null
      },
      {
        "id": "fairness_en_10",
        "title": "Ep 10 · Amanpur's Promise",
        "audioKey": "en/fairness/10_amanpurs_promise.ogg",
        "durationMs": 436172,
        "previewEndMs": null
      }
    ]
  },
  {
    "id": "gratitude_en",
    "title": "The Things We Never Notice",
    "description": "A 10-part story about gratitude.",
    "language": "english",
    "category": "moral",
    "cover": "gratitude",
    "episodes": [
      {
        "id": "gratitude_en_01",
        "title": "Ep 1 · The List That Wouldn’t End",
        "audioKey": "en/gratitude/01_the_list_that_wouldnt_end.ogg",
        "durationMs": 447625,
        "previewEndMs": 224644
      },
      {
        "id": "gratitude_en_02",
        "title": "Ep 2 · The Man at the Gate",
        "audioKey": "en/gratitude/02_the_man_at_the_gate.ogg",
        "durationMs": 377812,
        "previewEndMs": null
      },
      {
        "id": "gratitude_en_03",
        "title": "Ep 3 · The Teacher in the Photograph",
        "audioKey": "en/gratitude/03_the_teacher_in_the_photograph.ogg",
        "durationMs": 300767,
        "previewEndMs": null
      },
      {
        "id": "gratitude_en_04",
        "title": "Ep 4 · The Missing Page",
        "audioKey": "en/gratitude/04_the_missing_page.ogg",
        "durationMs": 318128,
        "previewEndMs": null
      },
      {
        "id": "gratitude_en_05",
        "title": "Ep 5 · When the House Went Quiet",
        "audioKey": "en/gratitude/05_when_the_house_went_quiet.ogg",
        "durationMs": 330392,
        "previewEndMs": null
      },
      {
        "id": "gratitude_en_06",
        "title": "Ep 6 · The Work We Never Saw",
        "audioKey": "en/gratitude/06_the_work_we_never_saw.ogg",
        "durationMs": 311438,
        "previewEndMs": null
      },
      {
        "id": "gratitude_en_07",
        "title": "Ep 7 · The Silver Key",
        "audioKey": "en/gratitude/07_the_silver_key.ogg",
        "durationMs": 244345,
        "previewEndMs": null
      },
      {
        "id": "gratitude_en_08",
        "title": "Ep 8 · The Woman Who Came Back",
        "audioKey": "en/gratitude/08_the_woman_who_came_back.ogg",
        "durationMs": 315637,
        "previewEndMs": null
      },
      {
        "id": "gratitude_en_09",
        "title": "Ep 9 · While They Can Hear You",
        "audioKey": "en/gratitude/09_while_they_can_hear_you.ogg",
        "durationMs": 259570,
        "previewEndMs": null
      },
      {
        "id": "gratitude_en_10",
        "title": "Ep 10 · The Children Who Notice",
        "audioKey": "en/gratitude/10_the_children_who_notice.ogg",
        "durationMs": 423055,
        "previewEndMs": null
      }
    ]
  },
  {
    "id": "honesty_en",
    "title": "The Book of Trust",
    "description": "A 10-part story about honesty.",
    "language": "english",
    "category": "moral",
    "cover": "honesty",
    "episodes": [
      {
        "id": "honesty_en_01",
        "title": "Ep 1 · The Missing Notebook",
        "audioKey": "en/honesty/01_the_missing_notebook.ogg",
        "durationMs": 375807,
        "previewEndMs": 189535
      },
      {
        "id": "honesty_en_02",
        "title": "Ep 2 · The Mysterious Footprints",
        "audioKey": "en/honesty/02_the_mysterious_footprints.ogg",
        "durationMs": 411908,
        "previewEndMs": null
      },
      {
        "id": "honesty_en_03",
        "title": "Ep 3 · The Blue Thread",
        "audioKey": "en/honesty/03_the_blue_thread.ogg",
        "durationMs": 340546,
        "previewEndMs": null
      },
      {
        "id": "honesty_en_04",
        "title": "Ep 4 · The Test of Trust",
        "audioKey": "en/honesty/04_the_test_of_trust.ogg",
        "durationMs": 293633,
        "previewEndMs": null
      },
      {
        "id": "honesty_en_05",
        "title": "Ep 5 · The Missing Money",
        "audioKey": "en/honesty/05_the_missing_money.ogg",
        "durationMs": 350188,
        "previewEndMs": null
      },
      {
        "id": "honesty_en_06",
        "title": "Ep 6 · The Shadow of Suspicion",
        "audioKey": "en/honesty/06_the_shadow_of_suspicion.ogg",
        "durationMs": 290757,
        "previewEndMs": null
      },
      {
        "id": "honesty_en_07",
        "title": "Ep 7 · The Phone That Changed Everything",
        "audioKey": "en/honesty/07_the_phone_that_changed_everything.ogg",
        "durationMs": 355004,
        "previewEndMs": null
      },
      {
        "id": "honesty_en_08",
        "title": "Ep 8 · The Empty Seat",
        "audioKey": "en/honesty/08_the_empty_seat.ogg",
        "durationMs": 326732,
        "previewEndMs": null
      },
      {
        "id": "honesty_en_09",
        "title": "Ep 9 · The Truth on the Screen",
        "audioKey": "en/honesty/09_the_truth_on_the_screen.ogg",
        "durationMs": 365073,
        "previewEndMs": null
      },
      {
        "id": "honesty_en_10",
        "title": "Ep 10 · When the Truth Was Revealed",
        "audioKey": "en/honesty/10_when_the_truth_was_revealed.ogg",
        "durationMs": 481154,
        "previewEndMs": null
      }
    ]
  },
  {
    "id": "kindness_en",
    "title": "The Kindness That Came Back",
    "description": "A 10-part story about kindness.",
    "language": "english",
    "category": "moral",
    "cover": "kindness",
    "episodes": [
      {
        "id": "kindness_en_01",
        "title": "Ep 1 · The Boy on the Bench",
        "audioKey": "en/kindness/01_the_boy_on_the_bench.ogg",
        "durationMs": 360683,
        "previewEndMs": 180894
      },
      {
        "id": "kindness_en_02",
        "title": "Ep 2 · Quiet Kindness",
        "audioKey": "en/kindness/02_quiet_kindness.ogg",
        "durationMs": 343391,
        "previewEndMs": null
      },
      {
        "id": "kindness_en_03",
        "title": "Ep 3 · The Space Between Questions",
        "audioKey": "en/kindness/03_the_space_between_questions.ogg",
        "durationMs": 308249,
        "previewEndMs": null
      },
      {
        "id": "kindness_en_04",
        "title": "Ep 4 · A Place at the Table",
        "audioKey": "en/kindness/04_a_place_at_the_table.ogg",
        "durationMs": 331585,
        "previewEndMs": null
      },
      {
        "id": "kindness_en_05",
        "title": "Ep 5 · The Day of Eid",
        "audioKey": "en/kindness/05_the_day_of_eid.ogg",
        "durationMs": 365332,
        "previewEndMs": null
      },
      {
        "id": "kindness_en_06",
        "title": "Ep 6 · A Door to Learning",
        "audioKey": "en/kindness/06_a_door_to_learning.ogg",
        "durationMs": 324759,
        "previewEndMs": null
      },
      {
        "id": "kindness_en_07",
        "title": "Ep 7 · When Kindness Needs Courage",
        "audioKey": "en/kindness/07_when_kindness_needs_courage.ogg",
        "durationMs": 324944,
        "previewEndMs": null
      },
      {
        "id": "kindness_en_08",
        "title": "Ep 8 · The Right Kind of Help",
        "audioKey": "en/kindness/08_the_right_kind_of_help.ogg",
        "durationMs": 302660,
        "previewEndMs": null
      },
      {
        "id": "kindness_en_09",
        "title": "Ep 9 · The Empty House",
        "audioKey": "en/kindness/09_the_empty_house.ogg",
        "durationMs": 315728,
        "previewEndMs": null
      },
      {
        "id": "kindness_en_10",
        "title": "Ep 10 · The Kindness That Came Back",
        "audioKey": "en/kindness/10_the_kindness_that_came_back.ogg",
        "durationMs": 461965,
        "previewEndMs": null
      }
    ]
  },
  {
    "id": "patience_en",
    "title": "The Things That Take Time",
    "description": "A 10-part story about patience.",
    "language": "english",
    "category": "moral",
    "cover": "patience",
    "episodes": [
      {
        "id": "patience_en_01",
        "title": "Ep 1 · Why Can’t It Happen Now?",
        "audioKey": "en/patience/01_why_cant_it_happen_now.ogg",
        "durationMs": 867161,
        "previewEndMs": 434993
      },
      {
        "id": "patience_en_02",
        "title": "Ep 2 · The Easy Way",
        "audioKey": "en/patience/02_the_easy_way.ogg",
        "durationMs": 889280,
        "previewEndMs": null
      },
      {
        "id": "patience_en_03",
        "title": "Ep 3 · Not Everything Has an Answer",
        "audioKey": "en/patience/03_not_everything_has_an_answer.ogg",
        "durationMs": 736515,
        "previewEndMs": null
      },
      {
        "id": "patience_en_04",
        "title": "Ep 4 · The First Step",
        "audioKey": "en/patience/04_the_first_step.ogg",
        "durationMs": 815105,
        "previewEndMs": null
      },
      {
        "id": "patience_en_05",
        "title": "Ep 5 · Three Days",
        "audioKey": "en/patience/05_three_days.ogg",
        "durationMs": 891160,
        "previewEndMs": null
      },
      {
        "id": "patience_en_06",
        "title": "Ep 6 · One Chance",
        "audioKey": "en/patience/06_one_chance.ogg",
        "durationMs": 799885,
        "previewEndMs": null
      },
      {
        "id": "patience_en_07",
        "title": "Ep 7 · The Door",
        "audioKey": "en/patience/07_the_door.ogg",
        "durationMs": 362039,
        "previewEndMs": null
      },
      {
        "id": "patience_en_08",
        "title": "Ep 8 · What Was Lost",
        "audioKey": "en/patience/08_what_was_lost.ogg",
        "durationMs": 472756,
        "previewEndMs": null
      },
      {
        "id": "patience_en_09",
        "title": "Ep 9 · The Missing Piece",
        "audioKey": "en/patience/09_the_missing_piece.ogg",
        "durationMs": 548714,
        "previewEndMs": null
      },
      {
        "id": "patience_en_10",
        "title": "Ep 10 · The Right Time",
        "audioKey": "en/patience/10_the_right_time.ogg",
        "durationMs": 635868,
        "previewEndMs": null
      }
    ]
  },
  {
    "id": "respect_en",
    "title": "Respect",
    "description": "A 10-part story about respect and dignity.",
    "language": "english",
    "category": "moral",
    "cover": "respect",
    "episodes": [
      {
        "id": "respect_en_01",
        "title": "Ep 1 · Rashid's Salam",
        "audioKey": "en/respect/01_rashids_salam.ogg",
        "durationMs": 417816,
        "previewEndMs": 259135
      },
      {
        "id": "respect_en_02",
        "title": "Ep 2 · Votes and Promises",
        "audioKey": "en/respect/02_votes_and_promises.ogg",
        "durationMs": 427259,
        "previewEndMs": null
      },
      {
        "id": "respect_en_03",
        "title": "Ep 3 · The First Loss",
        "audioKey": "en/respect/03_the_first_loss.ogg",
        "durationMs": 652558,
        "previewEndMs": null
      },
      {
        "id": "respect_en_04",
        "title": "Ep 4 · The Courage to Speak",
        "audioKey": "en/respect/04_the_courage_to_speak.ogg",
        "durationMs": 220588,
        "previewEndMs": null
      },
      {
        "id": "respect_en_05",
        "title": "Ep 5 · The Boy Behind the Badge",
        "audioKey": "en/respect/05_the_boy_behind_the_badge.ogg",
        "durationMs": 307020,
        "previewEndMs": null
      },
      {
        "id": "respect_en_06",
        "title": "Ep 6 · The Captain's Special Seat",
        "audioKey": "en/respect/06_the_captains_special_seat.ogg",
        "durationMs": 414590,
        "previewEndMs": null
      },
      {
        "id": "respect_en_07",
        "title": "Ep 7 · The Captain Learns to Listen",
        "audioKey": "en/respect/07_the_captain_learns_to_listen.ogg",
        "durationMs": 287365,
        "previewEndMs": null
      },
      {
        "id": "respect_en_08",
        "title": "Ep 8 · The Test of True Respect",
        "audioKey": "en/respect/08_the_test_of_true_respect.ogg",
        "durationMs": 244547,
        "previewEndMs": null
      },
      {
        "id": "respect_en_09",
        "title": "Ep 9 · The Choice That Changed Everything",
        "audioKey": "en/respect/09_the_choice_that_changed_everything.ogg",
        "durationMs": 425335,
        "previewEndMs": null
      },
      {
        "id": "respect_en_10",
        "title": "Ep 10 · The Man Behind the Notes",
        "audioKey": "en/respect/10_the_man_behind_the_notes.ogg",
        "durationMs": 691961,
        "previewEndMs": null
      }
    ]
  },
  {
    "id": "adam_ur",
    "title": "حضرت آدم علیہ السلام",
    "description": "حضرت آدم علیہ السلام پر 6 اقساط کی کہانی",
    "language": "urdu",
    "category": "prophets",
    "cover": "adam",
    "episodes": [
      {
        "id": "adam_ur_01",
        "title": "قسط 1 · پہلے قدم سے پہلے",
        "audioKey": "ur/adam/01.ogg",
        "durationMs": 387389,
        "previewEndMs": 195787
      },
      {
        "id": "adam_ur_02",
        "title": "قسط 2 · علم کا راز",
        "audioKey": "ur/adam/02.ogg",
        "durationMs": 338339,
        "previewEndMs": null
      },
      {
        "id": "adam_ur_03",
        "title": "قسط 3 · میں بہتر ہوں",
        "audioKey": "ur/adam/03.ogg",
        "durationMs": 289164,
        "previewEndMs": null
      },
      {
        "id": "adam_ur_04",
        "title": "قسط 4 · ممنوع درخت",
        "audioKey": "ur/adam/04.ogg",
        "durationMs": 294389,
        "previewEndMs": null
      },
      {
        "id": "adam_ur_05",
        "title": "قسط 5 · دروازہ ابھی کھلا تھا",
        "audioKey": "ur/adam/05.ogg",
        "durationMs": 353136,
        "previewEndMs": null
      },
      {
        "id": "adam_ur_06",
        "title": "قسط 6 · حسد کی آگ",
        "audioKey": "ur/adam/06.ogg",
        "durationMs": 464606,
        "previewEndMs": null
      }
    ]
  },
  {
    "id": "hud_ur",
    "title": "حضرت ہود علیہ السلام",
    "description": "تکبر، شکر اور عاجزی پر 5 اقساط کی کہانی",
    "language": "urdu",
    "category": "prophets",
    "cover": "hud",
    "episodes": [
      {
        "id": "hud_ur_01",
        "title": "قسط 1 · کوئی مجھے ہرا نہیں سکتا!",
        "audioKey": "ur/hud/01.ogg",
        "durationMs": 591320,
        "previewEndMs": 296223
      },
      {
        "id": "hud_ur_02",
        "title": "قسط 2 · دیکھو! ہم نے کیا بنایا ہے",
        "audioKey": "ur/hud/02.ogg",
        "durationMs": 481195,
        "previewEndMs": null
      },
      {
        "id": "hud_ur_03",
        "title": "قسط 3 · یہ سب تمہیں کس نے دیا؟",
        "audioKey": "ur/hud/03.ogg",
        "durationMs": 394046,
        "previewEndMs": null
      },
      {
        "id": "hud_ur_04",
        "title": "قسط 4 · اتنے مضبوط کہ مہربان بن سکیں",
        "audioKey": "ur/hud/04.ogg",
        "durationMs": 518587,
        "previewEndMs": null
      },
      {
        "id": "hud_ur_05",
        "title": "قسط 5 · جب طاقت کافی نہ رہی",
        "audioKey": "ur/hud/05.ogg",
        "durationMs": 629483,
        "previewEndMs": null
      }
    ]
  },
  {
    "id": "idris_ur",
    "title": "حضرت ادریس علیہ السلام",
    "description": "سچ پر قائم رہنے پر 3 اقساط کی کہانی",
    "language": "urdu",
    "category": "prophets",
    "cover": "idris",
    "episodes": [
      {
        "id": "idris_ur_01",
        "title": "قسط 1 · سچ پر قائم رہنے کی قیمت",
        "audioKey": "ur/idris/01.ogg",
        "durationMs": 833898,
        "previewEndMs": 419970
      },
      {
        "id": "idris_ur_02",
        "title": "قسط 2 · جب سچ بولنا مشکل ہو جائے",
        "audioKey": "ur/idris/02.ogg",
        "durationMs": 918655,
        "previewEndMs": null
      },
      {
        "id": "idris_ur_03",
        "title": "قسط 3 · بلند مقام",
        "audioKey": "ur/idris/03.ogg",
        "durationMs": 944388,
        "previewEndMs": null
      }
    ]
  },
  {
    "id": "nuh_ur",
    "title": "حضرت نوح علیہ السلام",
    "description": "صبر اور ہمت پر 6 اقساط کی کہانی",
    "language": "urdu",
    "category": "prophets",
    "cover": "nuh",
    "episodes": [
      {
        "id": "nuh_ur_01",
        "title": "قسط 1 · مقصد کیا تھا؟",
        "audioKey": "ur/nuh/01.ogg",
        "durationMs": 538826,
        "previewEndMs": 271009
      },
      {
        "id": "nuh_ur_02",
        "title": "قسط 2 · دوبارہ کوشش، نئے انداز سے",
        "audioKey": "ur/nuh/02.ogg",
        "durationMs": 485464,
        "previewEndMs": null
      },
      {
        "id": "nuh_ur_03",
        "title": "قسط 3 · جب لوگ ہنستے ہیں",
        "audioKey": "ur/nuh/03.ogg",
        "durationMs": 1083781,
        "previewEndMs": null
      },
      {
        "id": "nuh_ur_04",
        "title": "قسط 4 · صرف چند لوگ",
        "audioKey": "ur/nuh/04.ogg",
        "durationMs": 962981,
        "previewEndMs": null
      },
      {
        "id": "nuh_ur_05",
        "title": "قسط 5 · لوگ سمجھیں، اس سے پہلے",
        "audioKey": "ur/nuh/05.ogg",
        "durationMs": 1290665,
        "previewEndMs": null
      },
      {
        "id": "nuh_ur_06",
        "title": "قسط 6 · آخر کیا باقی رہ جاتا ہے؟",
        "audioKey": "ur/nuh/06.ogg",
        "durationMs": 1263373,
        "previewEndMs": null
      }
    ]
  },
  {
    "id": "salih_ur",
    "title": "حضرت صالح علیہ السلام",
    "description": "حدود، حقوق اور ذمہ داری پر 5 اقساط کی کہانی",
    "language": "urdu",
    "category": "prophets",
    "cover": "salih",
    "episodes": [
      {
        "id": "salih_ur_01",
        "title": "قسط 1 · ہر چیز کے لیے اصول کیوں ہیں؟",
        "audioKey": "ur/salih/01.ogg",
        "durationMs": 722847,
        "previewEndMs": 363983
      },
      {
        "id": "salih_ur_02",
        "title": "قسط 2 · لیکن مجھے بتائیں، کیوں؟",
        "audioKey": "ur/salih/02.ogg",
        "durationMs": 657871,
        "previewEndMs": null
      },
      {
        "id": "salih_ur_03",
        "title": "قسط 3 · یہ میری باری تھی",
        "audioKey": "ur/salih/03.ogg",
        "durationMs": 709522,
        "previewEndMs": null
      },
      {
        "id": "salih_ur_04",
        "title": "قسط 4 · امی کو کبھی پتا نہیں چلے گا",
        "audioKey": "ur/salih/04.ogg",
        "durationMs": 690453,
        "previewEndMs": null
      },
      {
        "id": "salih_ur_05",
        "title": "قسط 5 · اصول دشمن نہیں تھا",
        "audioKey": "ur/salih/05.ogg",
        "durationMs": 751286,
        "previewEndMs": null
      }
    ]
  },
  {
    "id": "fairness_ur",
    "title": "سنہری ترازو",
    "description": "انصاف پر 10 اقساط کی کہانی",
    "language": "urdu",
    "category": "moral",
    "cover": "fairness",
    "episodes": [
      {
        "id": "fairness_ur_01",
        "title": "قسط 1 · سنہری ترازو",
        "audioKey": "ur/fairness/01.ogg",
        "durationMs": 363433,
        "previewEndMs": 187321
      },
      {
        "id": "fairness_ur_02",
        "title": "قسط 2 · تصویر میں ایک سایہ",
        "audioKey": "ur/fairness/02.ogg",
        "durationMs": 303456,
        "previewEndMs": null
      },
      {
        "id": "fairness_ur_03",
        "title": "قسط 3 · کانسی کی چابی",
        "audioKey": "ur/fairness/03.ogg",
        "durationMs": 320696,
        "previewEndMs": null
      },
      {
        "id": "fairness_ur_04",
        "title": "قسط 4 · انصاف کا باغ",
        "audioKey": "ur/fairness/04.ogg",
        "durationMs": 288032,
        "previewEndMs": null
      },
      {
        "id": "fairness_ur_05",
        "title": "قسط 5 · انصاف کی راہ",
        "audioKey": "ur/fairness/05.ogg",
        "durationMs": 314048,
        "previewEndMs": null
      },
      {
        "id": "fairness_ur_06",
        "title": "قسط 6 · گم شدہ ترازو",
        "audioKey": "ur/fairness/06.ogg",
        "durationMs": 309681,
        "previewEndMs": null
      },
      {
        "id": "fairness_ur_07",
        "title": "قسط 7 · نمبر سترہ",
        "audioKey": "ur/fairness/07.ogg",
        "durationMs": 302897,
        "previewEndMs": null
      },
      {
        "id": "fairness_ur_08",
        "title": "قسط 8 · پوشیدہ راستہ",
        "audioKey": "ur/fairness/08.ogg",
        "durationMs": 355310,
        "previewEndMs": null
      },
      {
        "id": "fairness_ur_09",
        "title": "قسط 9 · امیدوار نمبر سترہ کا ریکارڈ",
        "audioKey": "ur/fairness/09.ogg",
        "durationMs": 376373,
        "previewEndMs": null
      },
      {
        "id": "fairness_ur_10",
        "title": "قسط 10 · امن پور کا عہد",
        "audioKey": "ur/fairness/10.ogg",
        "durationMs": 445476,
        "previewEndMs": null
      }
    ]
  },
  {
    "id": "gratitude_ur",
    "title": "وہ چیزیں جن پر ہماری نظر نہیں جاتی",
    "description": "شکرگزاری پر 10 اقساط کی کہانی",
    "language": "urdu",
    "category": "moral",
    "cover": "gratitude",
    "episodes": [
      {
        "id": "gratitude_ur_01",
        "title": "قسط 1 · وہ فہرست جو ختم ہونے کا نام نہ لیتی تھی",
        "audioKey": "ur/gratitude/01.ogg",
        "durationMs": 470613,
        "previewEndMs": 237877
      },
      {
        "id": "gratitude_ur_02",
        "title": "قسط 2 · گیٹ پر موجود شخص",
        "audioKey": "ur/gratitude/02.ogg",
        "durationMs": 350900,
        "previewEndMs": null
      },
      {
        "id": "gratitude_ur_03",
        "title": "قسط 3 · تصویر میں موجود استانی",
        "audioKey": "ur/gratitude/03.ogg",
        "durationMs": 299258,
        "previewEndMs": null
      },
      {
        "id": "gratitude_ur_04",
        "title": "قسط 4 · گم شدہ صفحہ",
        "audioKey": "ur/gratitude/04.ogg",
        "durationMs": 226796,
        "previewEndMs": null
      },
      {
        "id": "gratitude_ur_05",
        "title": "قسط 5 · جب گھر خاموش ہو گیا",
        "audioKey": "ur/gratitude/05.ogg",
        "durationMs": 277026,
        "previewEndMs": null
      },
      {
        "id": "gratitude_ur_06",
        "title": "قسط 6 · وہ کام جو ہماری نظروں سے اوجھل رہا",
        "audioKey": "ur/gratitude/06.ogg",
        "durationMs": 280528,
        "previewEndMs": null
      },
      {
        "id": "gratitude_ur_07",
        "title": "قسط 7 · چاندی کی چابی",
        "audioKey": "ur/gratitude/07.ogg",
        "durationMs": 221946,
        "previewEndMs": null
      },
      {
        "id": "gratitude_ur_08",
        "title": "قسط 8 · وہ خاتون جو واپس آئیں",
        "audioKey": "ur/gratitude/08.ogg",
        "durationMs": 271755,
        "previewEndMs": null
      },
      {
        "id": "gratitude_ur_09",
        "title": "قسط 9 · جب تک وہ سن سکتے ہیں",
        "audioKey": "ur/gratitude/09.ogg",
        "durationMs": 228545,
        "previewEndMs": null
      },
      {
        "id": "gratitude_ur_10",
        "title": "قسط 10 · وہ بچے جو توجہ دیتے ہیں",
        "audioKey": "ur/gratitude/10.ogg",
        "durationMs": 460791,
        "previewEndMs": null
      }
    ]
  },
  {
    "id": "honesty_ur",
    "title": "کتابِ امانت",
    "description": "سچائی پر 4 اقساط کی کہانی",
    "language": "urdu",
    "category": "moral",
    "cover": "honesty",
    "episodes": [
      {
        "id": "honesty_ur_01",
        "title": "قسط 1 · گم شدہ نوٹ بک",
        "audioKey": "ur/honesty/01.ogg",
        "durationMs": 400957,
        "previewEndMs": 202957
      },
      {
        "id": "honesty_ur_02",
        "title": "قسط 2 · پراسرار قدموں کے نشان",
        "audioKey": "ur/honesty/02.ogg",
        "durationMs": 362343,
        "previewEndMs": null
      },
      {
        "id": "honesty_ur_03",
        "title": "قسط 3 · نیلا دھاگا",
        "audioKey": "ur/honesty/03.ogg",
        "durationMs": 275979,
        "previewEndMs": null
      },
      {
        "id": "honesty_ur_04",
        "title": "قسط 4 · اعتماد کا امتحان",
        "audioKey": "ur/honesty/04.ogg",
        "durationMs": 118447,
        "previewEndMs": null
      }
    ]
  },
  {
    "id": "kindness_ur",
    "title": "وہ مہربانی جو لوٹ کر آئی",
    "description": "مہربانی پر 10 اقساط کی کہانی",
    "language": "urdu",
    "category": "moral",
    "cover": "kindness",
    "episodes": [
      {
        "id": "kindness_ur_01",
        "title": "قسط 1 · بنچ پر بیٹھا لڑکا",
        "audioKey": "ur/kindness/01.ogg",
        "durationMs": 366356,
        "previewEndMs": 183985
      },
      {
        "id": "kindness_ur_02",
        "title": "قسط 2 · خاموش مہربانی",
        "audioKey": "ur/kindness/02.ogg",
        "durationMs": 376798,
        "previewEndMs": null
      },
      {
        "id": "kindness_ur_03",
        "title": "قسط 3 · سوالوں کے درمیان کا فاصلہ",
        "audioKey": "ur/kindness/03.ogg",
        "durationMs": 338122,
        "previewEndMs": null
      },
      {
        "id": "kindness_ur_04",
        "title": "قسط 4 · دسترخوان پر ایک جگہ",
        "audioKey": "ur/kindness/04.ogg",
        "durationMs": 328403,
        "previewEndMs": null
      },
      {
        "id": "kindness_ur_05",
        "title": "قسط 5 · عید کا دن",
        "audioKey": "ur/kindness/05.ogg",
        "durationMs": 380977,
        "previewEndMs": null
      },
      {
        "id": "kindness_ur_06",
        "title": "قسط 6 · علم کی طرف ایک دروازہ",
        "audioKey": "ur/kindness/06.ogg",
        "durationMs": 348962,
        "previewEndMs": null
      },
      {
        "id": "kindness_ur_07",
        "title": "قسط 7 · جب مہربانی کے لیے ہمت چاہیے",
        "audioKey": "ur/kindness/07.ogg",
        "durationMs": 342680,
        "previewEndMs": null
      },
      {
        "id": "kindness_ur_08",
        "title": "قسط 8 · صحیح انداز کی مدد",
        "audioKey": "ur/kindness/08.ogg",
        "durationMs": 310967,
        "previewEndMs": null
      },
      {
        "id": "kindness_ur_09",
        "title": "قسط 9 · خالی گھر",
        "audioKey": "ur/kindness/09.ogg",
        "durationMs": 344421,
        "previewEndMs": null
      },
      {
        "id": "kindness_ur_10",
        "title": "قسط 10 · وہ مہربانی جو لوٹ کر آئی",
        "audioKey": "ur/kindness/10.ogg",
        "durationMs": 456370,
        "previewEndMs": null
      }
    ]
  },
  {
    "id": "patience_ur",
    "title": "جو چیزیں وقت لیتی ہیں",
    "description": "صبر پر 10 اقساط کی کہانی",
    "language": "urdu",
    "category": "moral",
    "cover": "patience",
    "episodes": [
      {
        "id": "patience_ur_01",
        "title": "قسط 1 · ابھی کیوں نہیں ہو سکتا؟",
        "audioKey": "ur/patience/01.ogg",
        "durationMs": 863530,
        "previewEndMs": 436666
      },
      {
        "id": "patience_ur_02",
        "title": "قسط 2 · آسان راستہ",
        "audioKey": "ur/patience/02.ogg",
        "durationMs": 907812,
        "previewEndMs": null
      },
      {
        "id": "patience_ur_03",
        "title": "قسط 3 · ہر چیز کا جواب نہیں ہوتا",
        "audioKey": "ur/patience/03.ogg",
        "durationMs": 767300,
        "previewEndMs": null
      },
      {
        "id": "patience_ur_04",
        "title": "قسط 4 · پہلا قدم",
        "audioKey": "ur/patience/04.ogg",
        "durationMs": 781011,
        "previewEndMs": null
      },
      {
        "id": "patience_ur_05",
        "title": "قسط 5 · تین دن",
        "audioKey": "ur/patience/05.ogg",
        "durationMs": 853921,
        "previewEndMs": null
      },
      {
        "id": "patience_ur_06",
        "title": "قسط 6 · ایک موقع",
        "audioKey": "ur/patience/06.ogg",
        "durationMs": 832299,
        "previewEndMs": null
      },
      {
        "id": "patience_ur_07",
        "title": "قسط 7 · دروازہ",
        "audioKey": "ur/patience/07.ogg",
        "durationMs": 394054,
        "previewEndMs": null
      },
      {
        "id": "patience_ur_08",
        "title": "قسط 8 · جو چیز کھو گئی تھی",
        "audioKey": "ur/patience/08.ogg",
        "durationMs": 480354,
        "previewEndMs": null
      },
      {
        "id": "patience_ur_09",
        "title": "قسط 9 · غائب حصہ",
        "audioKey": "ur/patience/09.ogg",
        "durationMs": 498921,
        "previewEndMs": null
      },
      {
        "id": "patience_ur_10",
        "title": "قسط 10 · صحیح وقت",
        "audioKey": "ur/patience/10.ogg",
        "durationMs": 658334,
        "previewEndMs": null
      }
    ]
  },
  {
    "id": "respect_ur",
    "title": "احترام",
    "description": "احترام اور عزتِ نفس پر 10 اقساط کی کہانی",
    "language": "urdu",
    "category": "moral",
    "cover": "respect",
    "episodes": [
      {
        "id": "respect_ur_01",
        "title": "قسط 1 · رشید کا سلام",
        "audioKey": "ur/respect/01.ogg",
        "durationMs": 430447,
        "previewEndMs": 217399
      },
      {
        "id": "respect_ur_02",
        "title": "قسط 2 · ووٹ اور وعدے",
        "audioKey": "ur/respect/02.ogg",
        "durationMs": 454646,
        "previewEndMs": null
      },
      {
        "id": "respect_ur_03",
        "title": "قسط 3 · پہلی شکست",
        "audioKey": "ur/respect/03.ogg",
        "durationMs": 460972,
        "previewEndMs": null
      },
      {
        "id": "respect_ur_04",
        "title": "قسط 4 · بولنے کی ہمت",
        "audioKey": "ur/respect/04.ogg",
        "durationMs": 230661,
        "previewEndMs": null
      },
      {
        "id": "respect_ur_05",
        "title": "قسط 5 · بیج کے پیچھے والا لڑکا",
        "audioKey": "ur/respect/05.ogg",
        "durationMs": 328736,
        "previewEndMs": null
      },
      {
        "id": "respect_ur_06",
        "title": "قسط 6 · کیپٹن کی خاص کرسی",
        "audioKey": "ur/respect/06.ogg",
        "durationMs": 450236,
        "previewEndMs": null
      },
      {
        "id": "respect_ur_07",
        "title": "قسط 7 · کیپٹن سننا سیکھتا ہے",
        "audioKey": "ur/respect/07.ogg",
        "durationMs": 285484,
        "previewEndMs": null
      },
      {
        "id": "respect_ur_08",
        "title": "قسط 8 · اصل احترام کا امتحان",
        "audioKey": "ur/respect/08.ogg",
        "durationMs": 260311,
        "previewEndMs": null
      },
      {
        "id": "respect_ur_09",
        "title": "قسط 9 · وہ انتخاب جس نے سب کچھ بدل دیا",
        "audioKey": "ur/respect/09.ogg",
        "durationMs": 482150,
        "previewEndMs": null
      },
      {
        "id": "respect_ur_10",
        "title": "قسط 10 · نوٹس کون لکھ رہا تھا؟",
        "audioKey": "ur/respect/10.ogg",
        "durationMs": 738243,
        "previewEndMs": null
      }
    ]
  }
];
