import 'series_intros.dart';
import 'story.dart';
import 'story_category.dart';

enum StoryLanguage { english, urdu }

extension StoryLanguageX on StoryLanguage {
  String get label => switch (this) {
    StoryLanguage.english => 'English',
    StoryLanguage.urdu => 'اردو',
  };
}

/// A narrated series: one cover and its episodes in order. Each episode is a
/// [Story], so playback, progress, favourites and captions work on them
/// exactly as on a single story.
class Series {
  final String id;
  final String title;
  final StoryLanguage language;
  final StoryCategory category;
  final String coverAsset;
  final String description;

  /// The spoken trailer cut from the recording. Still generated by
  /// tools/gen_series.dart but no longer played or listed: the written
  /// [intro] took its place.
  final Story? trailer;
  final List<Story> episodes;

  const Series({
    required this.id,
    required this.title,
    required this.language,
    required this.category,
    required this.coverAsset,
    required this.description,
    this.trailer,
    required this.episodes,
  });

  /// Everything in play order.
  List<Story> get tracks => episodes;

  /// The written introduction shown on the series page, if there is one.
  String? get intro => seriesIntros[id];

  String get episodeCountLabel => switch (language) {
    StoryLanguage.urdu => '${episodes.length} اقساط',
    StoryLanguage.english =>
      '${episodes.length} ${episodes.length == 1 ? 'episode' : 'episodes'}',
  };
}
