// GENERATED by tools/gen_series.dart from tools/series/honesty_ur.json.
// Do not edit by hand: change the config or script and rerun.
//
// Caption times come from aligning the script to a whisper
// transcript of the recording.

import '../series.dart';
import '../story.dart';
import '../story_category.dart';

const Series honestyUrdu = Series(
  id: 'honesty_ur',
  title: 'کتابِ امانت',
  language: StoryLanguage.urdu,
  category: StoryCategory.moral,
  coverAsset: 'assets/covers/honesty.webp',
  description: 'سچائی پر 4 اقساط کی کہانی',
  trailer: Story(
    id: 'honesty_ur_00',
    title: 'ٹریلر · کتابِ امانت',
    narrator: 'Imaan & Akhlaq',
    coverAsset: 'assets/covers/honesty.webp',
    audioAsset: 'assets/audio/ur/honesty/00_trailer.ogg',
    category: StoryCategory.moral,
    description: 'کتابِ امانت کا تعارف',
    captions: [
      CaptionLine(
        start: Duration(milliseconds: 0),
        end: Duration(milliseconds: 2000),
        text: 'ایمان و اخلاق',
      ),
      CaptionLine(
        start: Duration(milliseconds: 2000),
        end: Duration(milliseconds: 3800),
        text: 'کتابِ امانت',
      ),
      CaptionLine(
        start: Duration(milliseconds: 3800),
        end: Duration(milliseconds: 7060),
        text: 'سچائی پر دس ابواب پر مشتمل کہانی',
      ),
      CaptionLine(
        start: Duration(milliseconds: 7060),
        end: Duration(milliseconds: 8080),
        text: 'فہرست',
      ),
      CaptionLine(
        start: Duration(milliseconds: 8080),
        end: Duration(milliseconds: 11716),
        text: '1. گم شدہ نوٹ بک',
      ),
      CaptionLine(
        start: Duration(milliseconds: 11716),
        end: Duration(milliseconds: 13300),
        text: '2. پراسرار قدموں کے نشان',
      ),
      CaptionLine(
        start: Duration(milliseconds: 13765),
        end: Duration(milliseconds: 15160),
        text: '3. نیلا دھاگا',
      ),
      CaptionLine(
        start: Duration(milliseconds: 15601),
        end: Duration(milliseconds: 17660),
        text: '4. اعتماد کا امتحان',
      ),
      CaptionLine(
        start: Duration(milliseconds: 19198),
        end: Duration(milliseconds: 19660),
        text: '5. گم شدہ رقم',
      ),
      CaptionLine(
        start: Duration(milliseconds: 19967),
        end: Duration(milliseconds: 20856),
        text: '6. شک کا سایہ',
      ),
      CaptionLine(
        start: Duration(milliseconds: 21567),
        end: Duration(milliseconds: 24587),
        text: '7. وہ فون جس نے سب کچھ بدل دیا',
      ),
      CaptionLine(
        start: Duration(milliseconds: 24587),
        end: Duration(milliseconds: 26427),
        text: '8. خالی نشست',
      ),
      CaptionLine(
        start: Duration(milliseconds: 26427),
        end: Duration(milliseconds: 28587),
        text: '9. اسکرین پر سچائی',
      ),
      CaptionLine(
        start: Duration(milliseconds: 28587),
        end: Duration(milliseconds: 30927),
        text: '10. جب سچ سامنے آیا',
      ),
    ],
  ),
  episodes: [
    Story(
      id: 'honesty_ur_01',
      title: 'قسط 1 · گم شدہ نوٹ بک',
      narrator: 'Imaan & Akhlaq',
      coverAsset: 'assets/covers/honesty.webp',
      audioAsset: 'assets/audio/ur/honesty/01.ogg',
      category: StoryCategory.moral,
      description: 'کتابِ امانت — قسط 1 از 4',
      captions: [
        CaptionLine(
          start: Duration(milliseconds: 0),
          end: Duration(milliseconds: 651),
          text: 'باب اول',
        ),
        CaptionLine(
          start: Duration(milliseconds: 651),
          end: Duration(milliseconds: 2657),
          text: 'گم شدہ نوٹ بک',
        ),
        CaptionLine(
          start: Duration(milliseconds: 2657),
          end: Duration(milliseconds: 8457),
          text:
              'اخلاقی سبق: سچائی اس وقت بھی قائم رہتی ہے جب کوئی ہمیں دیکھ نہ رہا ہو۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 8565),
          end: Duration(milliseconds: 13245),
          text: 'شیخ انکل کی اکیڈمی میں پیر کی صبح کبھی خاموش نہیں ہوتی تھی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 13245),
          end: Duration(milliseconds: 23365),
          text:
              'کوئی گیٹ سے بھاگتا ہوا اندر آ رہا ہوتا، کوئی باغ میں فٹبال اچھال رہا ہوتا، اور کوئی آخری لمحے میں اپنا ہوم ورک مکمل کرنے کی کوشش کر رہا ہوتا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 24031),
          end: Duration(milliseconds: 30073),
          text:
              'پرانے سیب کے درخت کے نیچے شہزیب تین چھوٹے بچوں کو بڑی سنجیدگی سے سمجھا رہا تھا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 30573),
          end: Duration(milliseconds: 32493),
          text: '’’میرا ہوم ورک میں نے نہیں کھویا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 32733),
          end: Duration(milliseconds: 36333),
          text: 'میرا خیال ہے ایک بہت ذہین کبوتر اسے لے گیا ہے۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 36833),
          end: Duration(milliseconds: 40373),
          text: 'ایک بچے نے پوچھا، ’’کبوتر کو ہوم ورک کی کیا ضرورت تھی؟‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 40693),
          end: Duration(milliseconds: 43613),
          text: 'شہزیب نے جواب دیا، ’’تحقیق جاری ہے۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 44013),
          end: Duration(milliseconds: 45299),
          text: 'قریب کھڑا اخلاق ہنس پڑا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 46682),
          end: Duration(milliseconds: 50661),
          text:
              '’’آپی، شہزیب کے بہانے دن بہ دن زیادہ سائنسی ہوتے جا رہے ہیں۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 50661),
          end: Duration(milliseconds: 57461),
          text:
              'ایمان نے مسکرا کر کہا، ’’آپ بھی ذرا خیال رکھیے، کہیں اگلی بار اپنی جرابوں پر الزام نہ لگا دیں۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 57461),
          end: Duration(milliseconds: 63061),
          text:
              'کلاس روم کے اندر طارق فرش پر گری ہوئی کتابیں اٹھا کر شیلف میں رکھ رہا تھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 63061),
          end: Duration(milliseconds: 69172),
          text:
              'اسی وقت وسیم شیخ انکل کا حاضری رجسٹر اور رنگین چاک کا ڈبہ اٹھائے اندر آیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 69172),
          end: Duration(milliseconds: 73687),
          text:
              'اس نے کسی کے کہے بغیر دونوں چیزیں استاد کی میز پر سلیقے سے رکھ دیں۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 74189),
          end: Duration(milliseconds: 75666),
          text: 'ایک بچے نے کہا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 76338),
          end: Duration(milliseconds: 78889),
          text: '’’وسیم، تم ہر چیز پر نظر رکھتے ہو۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 78889),
          end: Duration(milliseconds: 80237),
          text: 'وسیم مسکرایا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 80237),
          end: Duration(milliseconds: 84693),
          text: '’’اگر کسی کا کام آسان ہو سکتا ہو تو مدد کیوں نہ کی جائے؟‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 84693),
          end: Duration(milliseconds: 86311),
          text: 'ایمان نے اسے دیکھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 86851),
          end: Duration(milliseconds: 87282),
          text: '’’ما شاء اللہ۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 87282),
          end: Duration(milliseconds: 90437),
          text: 'کوئی کہے بغیر مدد کرنا اچھی عادت ہے۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 90437),
          end: Duration(milliseconds: 92237),
          text: 'اخلاق نے سر ہلایا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 92237),
          end: Duration(milliseconds: 94757),
          text: '’’اور سچائی بھی ایسی ہی ہونی چاہیے، آپی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 94757),
          end: Duration(milliseconds: 97237),
          text: 'صرف تب نہیں جب کوئی پکڑ لے۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 97694),
          end: Duration(milliseconds: 102717),
          text:
              'صبح کے سبق کے بعد شیخ انکل ایک خوبصورت بھوری نوٹ بک لے کر کلاس میں آئے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 102717),
          end: Duration(milliseconds: 106837),
          text: 'اس کی جلد کے کنارے سے باریک نیلا فیتہ لٹک رہا تھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 106837),
          end: Duration(milliseconds: 108304),
          text: '’’السلام علیکم، بچو!‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 109091),
          end: Duration(milliseconds: 112405),
          text: '’’وعلیکم السلام، شیخ انکل!‘‘ پوری کلاس نے جواب دیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 112405),
          end: Duration(milliseconds: 114405),
          text: 'انہوں نے نوٹ بک میز پر رکھی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 114405),
          end: Duration(milliseconds: 117405),
          text: '’’یہ ہماری نئی کتابِ امانت ہے۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 117405),
          end: Duration(milliseconds: 119405),
          text: 'بچے فوراً متوجہ ہو گئے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 119405),
          end: Duration(milliseconds: 125405),
          text:
              '’’ہر جمعہ ایک طالب علم اس میں اپنی زندگی کا کوئی سچا اور ایماندارانہ فیصلہ لکھے گا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 125405),
          end: Duration(milliseconds: 128373),
          text: 'ضروری نہیں کہ کوئی بہت بڑا کام ہو۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 128373),
          end: Duration(milliseconds: 138773),
          text:
              'زائد رقم واپس کرنا، اپنی غلطی مان لینا، نقل سے انکار کرنا، یا بہانہ بنانا آسان ہو پھر بھی سچ بول دینا، سب اس میں شامل ہو سکتے ہیں۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 138773),
          end: Duration(milliseconds: 140933),
          text: 'شہزیب نے فوراً ہاتھ اٹھایا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 140933),
          end: Duration(milliseconds: 145202),
          text:
              '’’کیا میں اس ایماندار کبوتر کے بارے میں لکھ سکتا ہوں جس نے میرا ہوم ورک—‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 145453),
          end: Duration(milliseconds: 148341),
          text: 'شیخ انکل نے بات مکمل ہونے سے پہلے کہا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 148341),
          end: Duration(milliseconds: 153461),
          text: '’’صرف اس صورت میں جب کبوتر بطور گواہ دستخط بھی کرے۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 153461),
          end: Duration(milliseconds: 155538),
          text: 'کلاس قہقہے سے بھر گئی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 156316),
          end: Duration(milliseconds: 159301),
          text: 'شیخ انکل بھی مسکرائے، پھر سنجیدہ ہوئے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 159861),
          end: Duration(milliseconds: 162941),
          text: '’’بچو، اعتماد ایک دن میں نہیں بنتا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 162941),
          end: Duration(milliseconds: 171389),
          text:
              'مسلسل سچائی اور امانت داری انسان کے کردار کو ایسا بناتی ہے کہ لوگ اس کی بات پر بھروسا کرنے لگتے ہیں۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 171389),
          end: Duration(milliseconds: 175421),
          text: 'میں چاہتا ہوں یہ کتاب ایسے ہی فیصلوں کو محفوظ کرے۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 177098),
          end: Duration(milliseconds: 178941),
          text: 'نوٹ بک صبح بھر استاد کی میز پر رہی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 179780),
          end: Duration(milliseconds: 183309),
          text: 'دوپہر کے وقفے میں تقریباً سب بچے باہر چلے گئے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 183774),
          end: Duration(milliseconds: 186909),
          text: 'طارق بلال کے ساتھ فٹبال گراؤنڈ کی طرف گیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 186909),
          end: Duration(milliseconds: 192477),
          text:
              'ایمان اور اخلاق چھوٹے بچوں کی پانی کی بوتلیں بھرنے میں مدد کر رہے تھے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 193692),
          end: Duration(milliseconds: 198477),
          text:
              'وسیم مشق کی کاپیوں کا ایک ڈھیر اٹھا کر دفتر کی راہداری کی طرف چلا گیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 198877),
          end: Duration(milliseconds: 199980),
          text: 'وقفہ ختم ہوا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 199980),
          end: Duration(milliseconds: 202957),
          text: 'اسلامیات کی استاد میز کے پاس آئیں۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 203317),
          end: Duration(milliseconds: 205215),
          text: 'ان کا ہاتھ وہیں رک گیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 205215),
          end: Duration(milliseconds: 207113),
          text: 'انہوں نے کاغذ اٹھائے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 207113),
          end: Duration(milliseconds: 208117),
          text: 'دراز دیکھی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 208245),
          end: Duration(milliseconds: 209912),
          text: 'پھر دوبارہ میز۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 209912),
          end: Duration(milliseconds: 210745),
          text: '’’شیخ انکل؟‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 210745),
          end: Duration(milliseconds: 213245),
          text: 'وہ راہداری سے اندر آئے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 213245),
          end: Duration(milliseconds: 214630),
          text: 'استاد نے کہا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 215322),
          end: Duration(milliseconds: 216845),
          text: '’’کتابِ امانت غائب ہے۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 216845),
          end: Duration(milliseconds: 220445),
          text: 'ایک لمحے میں پوری کلاس کا ماحول بدل گیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 221088),
          end: Duration(milliseconds: 221860),
          text: 'کرسیاں کھسکنے لگیں۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 222245),
          end: Duration(milliseconds: 228125),
          text:
              'بچوں نے میزوں کے نیچے، پردوں کے پیچھے اور شیلفوں کے درمیان تلاش شروع کر دی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 228213),
          end: Duration(milliseconds: 229272),
          text: 'کچھ نہیں ملا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 229272),
          end: Duration(milliseconds: 231813),
          text: 'پھر پیچھے سے وسیم کی آواز آئی:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 231813),
          end: Duration(milliseconds: 236113),
          text: '’’میں نے وقفے میں کسی کو استاد کی میز کے قریب دیکھا تھا۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 236113),
          end: Duration(milliseconds: 237433),
          text: 'سب رک گئے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 238386),
          end: Duration(milliseconds: 239497),
          text: 'شیخ انکل نے پوچھا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 239497),
          end: Duration(milliseconds: 239973),
          text: '’’کسے؟‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 240613),
          end: Duration(milliseconds: 242533),
          text: 'وسیم چند لمحے خاموش رہا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 242533),
          end: Duration(milliseconds: 244873),
          text: '’’میں نے صرف پیچھے سے دیکھا تھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 244873),
          end: Duration(milliseconds: 246813),
          text: 'ممکن ہے میں غلط ہوں۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 246813),
          end: Duration(milliseconds: 248825),
          text: 'پھر اس نے طارق کی طرف دیکھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 248825),
          end: Duration(milliseconds: 251399),
          text: '’’لیکن مجھے لگا وہ طارق تھا۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 251914),
          end: Duration(milliseconds: 253330),
          text: 'طارق کا چہرہ تن گیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 253330),
          end: Duration(milliseconds: 255261),
          text: '’’میں نے کتاب نہیں لی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 255261),
          end: Duration(milliseconds: 256532),
          text: 'میں باہر تھا۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 256532),
          end: Duration(milliseconds: 258791),
          text: 'سب کی نظر بلال پر گئی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 258791),
          end: Duration(milliseconds: 261332),
          text: 'بلال نے بے آرامی سے کہا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 261332),
          end: Duration(milliseconds: 265375),
          text: '’’وہ کچھ دیر میرے ساتھ تھا... لیکن پورا وقفہ نہیں۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 265375),
          end: Duration(milliseconds: 268149),
          text: 'کلاس میں عجیب سی خاموشی پھیل گئی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 268149),
          end: Duration(milliseconds: 270774),
          text: 'شیخ انکل نے فوراً ہاتھ اٹھایا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 271687),
          end: Duration(milliseconds: 272030),
          text: '’’یہیں رک جاؤ۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 272030),
          end: Duration(milliseconds: 276709),
          text: 'کسی کا کسی جگہ نظر آ جانا اس کے مجرم ہونے کا ثبوت نہیں۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 276709),
          end: Duration(milliseconds: 280669),
          text: 'کوئی شخص اپنے اندازے کو الزام میں تبدیل نہیں کرے گا۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 281143),
          end: Duration(milliseconds: 282447),
          text: 'طارق نے سر جھکا لیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 282447),
          end: Duration(milliseconds: 284935),
          text: 'کسی نے اسے چور نہیں کہا تھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 284935),
          end: Duration(milliseconds: 290405),
          text: 'لیکن وہ محسوس کر رہا تھا کہ کمرے کی نظروں میں کچھ بدل چکا ہے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 290405),
          end: Duration(milliseconds: 294257),
          text: 'اس شام گھر پہنچ کر اس نے معمول سے کم بات کی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 294257),
          end: Duration(milliseconds: 297352),
          text: 'اس کی دادی نے فوراً محسوس کر لیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 297352),
          end: Duration(milliseconds: 298125),
          text: '’’کیا ہوا؟‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 298641),
          end: Duration(milliseconds: 300317),
          text: 'طارق نے سب کچھ بتا دیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 300317),
          end: Duration(milliseconds: 304122),
          text: 'دادی نے درمیان میں ایک لفظ بھی نہیں کہا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 304122),
          end: Duration(milliseconds: 305104),
          text: 'پھر بولیں:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 305104),
          end: Duration(milliseconds: 312945),
          text:
              '’’بیٹا، کبھی کبھی سچ کا امتحان اس وقت شروع ہوتا ہے جب ابھی کسی کو معلوم ہی نہیں ہوتا کہ سچ کیا ہے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 312945),
          end: Duration(milliseconds: 318045),
          text:
              'تمہارا کام یہ ہے کہ لوگوں کی الجھن تمہیں جھوٹ کی طرف نہ لے جائے۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 318540),
          end: Duration(milliseconds: 319405),
          text: 'طارق نے پوچھا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 319405),
          end: Duration(milliseconds: 322425),
          text: '’’لیکن اگر کوئی مجھ پر یقین ہی نہ کرے؟‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 322425),
          end: Duration(milliseconds: 324425),
          text: 'دادی نے نرمی سے کہا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 324425),
          end: Duration(milliseconds: 328053),
          text: '’’لوگ جانیں یا نہ جانیں، اللہ جانتا ہے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 328053),
          end: Duration(milliseconds: 332353),
          text: 'دوسروں کا شک تمہیں اپنی سچائی چھوڑنے پر مجبور نہ کرے۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 332353),
          end: Duration(milliseconds: 337513),
          text: 'اسی شام شیخ انکل اکیڈمی کا مرکزی گیٹ بند کرنے آئے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 337513),
          end: Duration(milliseconds: 342933),
          text: 'گیٹ کے دھاتی دستے کے گرد ایک سفید کاغذ تہہ کیا ہوا تھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 342933),
          end: Duration(milliseconds: 345713),
          text: 'انہوں نے اسے احتیاط سے کھولا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 345713),
          end: Duration(milliseconds: 348021),
          text: 'صرف ایک جملہ لکھا تھا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 348021),
          end: Duration(milliseconds: 351481),
          text: '’’سچ اپنے قدموں کے نشان چھوڑتا ہے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 351481),
          end: Duration(milliseconds: 353141),
          text: 'ان کا پیچھا کرو۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 353141),
          end: Duration(milliseconds: 356041),
          text: 'شیخ انکل نے باغ کی طرف دیکھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 356041),
          end: Duration(milliseconds: 361021),
          text: 'پھولوں کی کیاری کے پاس زمین ابھی صبح کے پانی سے نم تھی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 361021),
          end: Duration(milliseconds: 367061),
          text:
              'چھوٹے جوتوں کے نشان وہاں سے شروع ہو کر دفتر کی راہداری تک جا رہے تھے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 367061),
          end: Duration(milliseconds: 370424),
          text: 'آخری نشان دفتر کے دروازے پر ختم ہوا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 370424),
          end: Duration(milliseconds: 375049),
          text: 'اس کے پاس نیلے دھاگے کا ایک چھوٹا سا ٹکڑا پڑا تھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 375049),
          end: Duration(milliseconds: 378496),
          text: 'آج کا چیلنج: ایک چھوٹی سچائی بولیں',
        ),
        CaptionLine(
          start: Duration(milliseconds: 378496),
          end: Duration(milliseconds: 387951),
          text:
              'آج کوئی ایسی چھوٹی غلطی تسلیم کریں جسے چھپانا آسان ہو، مثلاً بھولا ہوا کام، ٹوٹی ہوئی چیز یا ادھوری ذمہ داری۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 387957),
          end: Duration(milliseconds: 391653),
          text: 'بہانہ بنائے بغیر سادہ انداز میں سچ کہہ دیں۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 392291),
          end: Duration(milliseconds: 393438),
          text: 'ایک قدم آگے',
        ),
        CaptionLine(
          start: Duration(milliseconds: 393438),
          end: Duration(milliseconds: 395732),
          text: 'صرف سچ بولنے پر نہ رکیں۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 395732),
          end: Duration(milliseconds: 400957),
          text: 'اپنی غلطی درست کرنے کے لیے ایک عملی قدم بھی اٹھائیں۔',
        ),
      ],
    ),
    Story(
      id: 'honesty_ur_02',
      title: 'قسط 2 · پراسرار قدموں کے نشان',
      narrator: 'Imaan & Akhlaq',
      coverAsset: 'assets/covers/honesty.webp',
      audioAsset: 'assets/audio/ur/honesty/02.ogg',
      category: StoryCategory.moral,
      description: 'کتابِ امانت — قسط 2 از 4',
      captions: [
        CaptionLine(
          start: Duration(milliseconds: 0),
          end: Duration(milliseconds: 882),
          text: 'باب دوم',
        ),
        CaptionLine(
          start: Duration(milliseconds: 1805),
          end: Duration(milliseconds: 3497),
          text: 'پراسرار قدموں کے نشان',
        ),
        CaptionLine(
          start: Duration(milliseconds: 3497),
          end: Duration(milliseconds: 6927),
          text: 'اخلاقی سبق: شک کو حقیقت میں تبدیل نہ کریں۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 6927),
          end: Duration(milliseconds: 16927),
          text:
              'اگلی صبح تک تقریباً پوری اکیڈمی کو گم شدہ کتاب، پراسرار نوٹ اور قدموں کے نشان کا علم ہو چکا تھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 16927),
          end: Duration(milliseconds: 20600),
          text: 'اب یہ صرف ایک گم شدہ نوٹ بک نہیں رہی تھی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 20600),
          end: Duration(milliseconds: 22927),
          text: 'یہ ایک معمہ بن چکی تھی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 22927),
          end: Duration(milliseconds: 26895),
          text: 'کلاس شروع ہونے سے پہلے بچے باغ میں جمع تھے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 26895),
          end: Duration(milliseconds: 33575),
          text:
              'رات بھر میں قدموں کے نشان کافی مدھم ہو چکے تھے، لیکن ایک نشان ابھی بھی واضح تھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 33815),
          end: Duration(milliseconds: 40415),
          text:
              'جوتے کے بیرونی کنارے میں ہلال جیسی ایک چھوٹی سی جگہ خالی تھی، جیسے ربڑ کا ایک ٹکڑا ٹوٹ گیا ہو۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 40735),
          end: Duration(milliseconds: 42455),
          text: 'اخلاق زمین پر بیٹھ گیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 42815),
          end: Duration(milliseconds: 43487),
          text: '’’آپی، یہ دیکھیے۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 44535),
          end: Duration(milliseconds: 46207),
          text: 'شہزیب نے فوراً اپنے جوتے دیکھے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 46863),
          end: Duration(milliseconds: 51443),
          text:
              '’’براہ کرم سرکاری ریکارڈ میں لکھ لیں کہ میرے جوتے بے قصور ہیں۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 51443),
          end: Duration(milliseconds: 53083),
          text: 'ایمان مسکرا دی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 53083),
          end: Duration(milliseconds: 55748),
          text: 'اس نے اپنی نوٹ بک میں نشان کا خاکہ بنا لیا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 55748),
          end: Duration(milliseconds: 57683),
          text: 'بیضوی ایڑی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 57683),
          end: Duration(milliseconds: 58773),
          text: 'آگے کا حصہ قدرے باریک۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 59863),
          end: Duration(milliseconds: 62683),
          text: 'بیرونی کنارے پر ہلال جیسی کمی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 63368),
          end: Duration(milliseconds: 65083),
          text: 'شیخ انکل نے سب کو اندر بلایا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 65083),
          end: Duration(milliseconds: 75271),
          text:
              '’’میں جانتا ہوں تم سب متجسس ہو، مگر تجسس تمہیں دوسروں کے بستے کھولنے، اجازت کے بغیر ان کے جوتے دیکھنے یا افواہیں پھیلانے کا حق نہیں دیتا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 75271),
          end: Duration(milliseconds: 78831),
          text: 'قرآن ہمیں بہت سے گمانوں سے بچنے کی تعلیم دیتا ہے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 78831),
          end: Duration(milliseconds: 81711),
          text: 'ہم شور نہیں، حقائق تلاش کریں گے۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 81711),
          end: Duration(milliseconds: 84431),
          text: 'اسی وقت طارق کلاس میں داخل ہوا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 84431),
          end: Duration(milliseconds: 88962),
          text:
              'دو بچے جو آہستہ آہستہ بات کر رہے تھے، اسے دیکھ کر خاموش ہو گئے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 89417),
          end: Duration(milliseconds: 90783),
          text: 'طارق نے کچھ نہیں کہا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 90783),
          end: Duration(milliseconds: 92719),
          text: 'اپنی جگہ جا کر بیٹھ گیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 93223),
          end: Duration(milliseconds: 95039),
          text: 'وسیم اس کے ساتھ والی کرسی پر آ بیٹھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 95644),
          end: Duration(milliseconds: 97359),
          text: '’’ان سب کو نظر انداز کرو۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 97803),
          end: Duration(milliseconds: 99137),
          text: 'طارق نے آہستہ سے کہا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 99803),
          end: Duration(milliseconds: 101248),
          text: '’’تمہارے لیے کہنا آسان ہے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 101248),
          end: Duration(milliseconds: 103359),
          text: 'سب تم پر بھروسا کرتے ہیں۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 103939),
          end: Duration(milliseconds: 105797),
          text: 'وسیم نے مسکرا کر جواب دیا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 105797),
          end: Duration(milliseconds: 110487),
          text:
              '’’جب تک تمہارا اعتماد واپس آتا ہے، میرا کچھ اعتماد ادھار لے لو۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 110882),
          end: Duration(milliseconds: 112364),
          text: 'طارق کے چہرے پر پہلی بار ہلکی سی مسکراہٹ آئی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 113847),
          end: Duration(milliseconds: 119767),
          text:
              'دوپہر کے وقفے میں وہ کھیل کے میدان سے ہٹ کر پرانے سیب کے درخت کے پاس جا بیٹھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 119767),
          end: Duration(milliseconds: 123287),
          text: 'محسن اور محسنہ وہاں بچوں سے ملنے آئے ہوئے تھے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 123287),
          end: Duration(milliseconds: 125247),
          text: 'محسن نے اسے دیکھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 125247),
          end: Duration(milliseconds: 127047),
          text: '’’السلام علیکم، طارق۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 127047),
          end: Duration(milliseconds: 128588),
          text: '’’وعلیکم السلام۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 128588),
          end: Duration(milliseconds: 130935),
          text: 'محسن نے اس کا چہرہ دیکھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 130935),
          end: Duration(milliseconds: 135135),
          text: '’’ایسے لگ رہے ہو جیسے کسی نے کھانے میں کڑوی دوا ملا دی ہو۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 135594),
          end: Duration(milliseconds: 137775),
          text: 'طارق نے انہیں پوری بات بتا دی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 137775),
          end: Duration(milliseconds: 140575),
          text: 'محسن نے تربوز کا ایک بیج اٹھایا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 140575),
          end: Duration(milliseconds: 146295),
          text:
              '’’اگر میں اسے ابھی زمین میں دبا دوں تو کیا عصر سے پہلے پوری بیل نکل آئے گی؟‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 147183),
          end: Duration(milliseconds: 147903),
          text: 'طارق تقریباً ہنس پڑا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 148503),
          end: Duration(milliseconds: 149503),
          text: '’’نہیں۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 149503),
          end: Duration(milliseconds: 150903),
          text: 'محسن نے کہا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 150903),
          end: Duration(milliseconds: 153583),
          text: '’’کبھی کبھی سچ بھی ایسا ہی لگتا ہے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 154157),
          end: Duration(milliseconds: 158343),
          text:
              'جھوٹی بات جلدی پھیل جاتی ہے، کیونکہ لوگ اسے بار بار دہراتے ہیں۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 158343),
          end: Duration(milliseconds: 163543),
          text: 'سچ کو سامنے آنے کے لیے کبھی صبر، ثبوت اور وقت چاہیے ہوتا ہے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 163543),
          end: Duration(milliseconds: 166588),
          text: 'لیکن آہستہ سامنے آنا، کمزور ہونا نہیں۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 167121),
          end: Duration(milliseconds: 171506),
          text:
              'واپس کلاس میں ایمان اور اخلاق نے اپنی تحقیق کے لیے ایک اصول بنایا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 172631),
          end: Duration(milliseconds: 175671),
          text: 'صرف وہ لکھیں گے جو واقعی معلوم ہو۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 175671),
          end: Duration(milliseconds: 177956),
          text: 'ایمان نے صفحے پر لکھا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 177956),
          end: Duration(milliseconds: 178671),
          text: 'معلوم:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 178671),
          end: Duration(milliseconds: 180671),
          text: '• کتابِ امانت غائب ہے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 180671),
          end: Duration(milliseconds: 182292),
          text: '• ایک سفید نوٹ ملا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 182698),
          end: Duration(milliseconds: 185671),
          text: '• باغ سے دفتر تک قدموں کے نشان گئے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 185671),
          end: Duration(milliseconds: 186371),
          text: '• ایک نشان کے کنارے پر ہلال جیسی کمی ہے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 186371),
          end: Duration(milliseconds: 186986),
          text: 'اخلاق نے اگلا عنوان لکھا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 186986),
          end: Duration(milliseconds: 187109),
          text: 'نامعلوم:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 187109),
          end: Duration(milliseconds: 187580),
          text: '• نوٹ کس نے لکھا؟',
        ),
        CaptionLine(
          start: Duration(milliseconds: 195175),
          end: Duration(milliseconds: 196346),
          text: '• قدموں کے نشان کس کے ہیں؟',
        ),
        CaptionLine(
          start: Duration(milliseconds: 196639),
          end: Duration(milliseconds: 197815),
          text: '• کتاب کس نے لی؟',
        ),
        CaptionLine(
          start: Duration(milliseconds: 197815),
          end: Duration(milliseconds: 200639),
          text: '• کیا تینوں کام ایک ہی شخص نے کیے؟',
        ),
        CaptionLine(
          start: Duration(milliseconds: 200639),
          end: Duration(milliseconds: 202639),
          text: 'اخلاق اچانک رک گیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 202639),
          end: Duration(milliseconds: 210447),
          text:
              '’’آپی، میں ابھی یہ لکھنے والا تھا کہ قدموں کے نشان اسی شخص کے ہیں جس نے نوٹ لکھا اور کتاب لی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 210447),
          end: Duration(milliseconds: 212907),
          text: 'لیکن... یہ ثابت تو نہیں۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 212907),
          end: Duration(milliseconds: 212908),
          text: 'ایمان نے کہا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 212908),
          end: Duration(milliseconds: 213513),
          text: '’’بالکل۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 213513),
          end: Duration(milliseconds: 216907),
          text: 'اپنی بات خود درست کرنا بھی سچائی ہے۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 216907),
          end: Duration(milliseconds: 218129),
          text: 'اخلاق نے سینہ پھلایا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 218907),
          end: Duration(milliseconds: 222347),
          text: '’’میں تیزی سے بہترین جاسوس بنتا جا رہا ہوں۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 222347),
          end: Duration(milliseconds: 223907),
          text: 'ایمان نے اسے دیکھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 223907),
          end: Duration(milliseconds: 228200),
          text:
              '’’کل آپ نے اپنی جرابوں پر الزام لگایا تھا کہ وہ خود چھپ گئی تھیں۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 228575),
          end: Duration(milliseconds: 230575),
          text: 'اخلاق سنجیدہ ہو گیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 231045),
          end: Duration(milliseconds: 232575),
          text: '’’آپی، وہ الگ مقدمہ تھا۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 232575),
          end: Duration(milliseconds: 235575),
          text: 'اسی دوپہر شیخ انکل نے دفتر دوبارہ دیکھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 235575),
          end: Duration(milliseconds: 242575),
          text:
              'نچلی دراز کے پاس انہیں وہ نیلا دھاگا ملا جو رات کو دروازے کے قریب دکھائی دیا تھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 242575),
          end: Duration(milliseconds: 244575),
          text: 'وہ عام بیگ کی سلائی سے مختلف تھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 244575),
          end: Duration(milliseconds: 247908),
          text: 'چپٹا، ہموار اور قدرے چمکدار۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 247908),
          end: Duration(milliseconds: 250743),
          text: 'تقریباً کسی فیتے یا لانیارڈ جیسا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 250743),
          end: Duration(milliseconds: 254183),
          text: 'انہوں نے اسے ایک شفاف لفافے میں محفوظ کر لیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 254637),
          end: Duration(milliseconds: 256343),
          text: 'طارق کی نظر دھاگے پر پڑی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 256343),
          end: Duration(milliseconds: 258009),
          text: 'پھر اپنے نیلے بیگ پر۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 258009),
          end: Duration(milliseconds: 261343),
          text: 'اس کے بیگ کی ایک سلائی واقعی اکھڑی ہوئی تھی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 261343),
          end: Duration(milliseconds: 263223),
          text: 'چند بچوں نے بھی دیکھ لیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 263223),
          end: Duration(milliseconds: 264711),
          text: 'ایک سرگوشی اٹھی:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 264711),
          end: Duration(milliseconds: 266543),
          text: '’’اس کا بیگ بھی نیلا ہے۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 267741),
          end: Duration(milliseconds: 268151),
          text: 'وسیم فوراً مڑا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 268151),
          end: Duration(milliseconds: 270711),
          text: '’’اکیڈمی میں بہت سی چیزیں نیلی ہیں۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 270711),
          end: Duration(milliseconds: 273111),
          text: 'صرف رنگ سے کچھ ثابت نہیں ہوتا۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 273801),
          end: Duration(milliseconds: 274261),
          text: 'شیخ انکل نے سر ہلایا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 274951),
          end: Duration(milliseconds: 275751),
          text: '’’بالکل۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 275751),
          end: Duration(milliseconds: 278071),
          text: 'رنگ کسی شخص کی شناخت نہیں۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 278071),
          end: Duration(milliseconds: 280791),
          text: 'ایمان نے طارق کے بیگ کے ریشے دیکھے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 280791),
          end: Duration(milliseconds: 282911),
          text: 'وہ موٹے اور کھردرے تھے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 282911),
          end: Duration(milliseconds: 285911),
          text: 'سراغ والا دھاگا باریک اور ہموار تھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 285911),
          end: Duration(milliseconds: 287900),
          text: 'اس نے یہ فرق بھی لکھ لیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 287900),
          end: Duration(milliseconds: 290439),
          text: 'چھٹی کے وقت طارق نے وسیم سے کہا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 290439),
          end: Duration(milliseconds: 292373),
          text: '’’میرے لیے بولنے کا شکریہ۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 292882),
          end: Duration(milliseconds: 293799),
          text: 'وسیم نے جواب دیا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 294029),
          end: Duration(milliseconds: 295984),
          text: '’’تم میرے لیے بھی یہی کرتے۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 295984),
          end: Duration(milliseconds: 296559),
          text: 'وہ مڑا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 296559),
          end: Duration(milliseconds: 299919),
          text: 'اس کے گلے میں اسکول کا شناختی کارڈ لٹک رہا تھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 301385),
          end: Duration(milliseconds: 302319),
          text: 'لانیارڈ گہرا نیلا تھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 302319),
          end: Duration(milliseconds: 304479),
          text: 'ایمان کی نظر اس پر پڑی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 304479),
          end: Duration(milliseconds: 306447),
          text: 'مگر اس نے کچھ نہیں کہا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 306447),
          end: Duration(milliseconds: 308976),
          text: 'نیلا ابھی صرف ایک رنگ تھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 308976),
          end: Duration(milliseconds: 314667),
          text: 'اس رات اکیڈمی کی چار دیواری کے باہر دو شناسا سائے کھڑے تھے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 315174),
          end: Duration(milliseconds: 317330),
          text: 'حاسد نے دھیمی آواز میں کہا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 317837),
          end: Duration(milliseconds: 320247),
          text: '’’اب بھی اس پر اعتماد کیا جا رہا ہے۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 320247),
          end: Duration(milliseconds: 321747),
          text: 'کاذب ہنسا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 321747),
          end: Duration(milliseconds: 326415),
          text:
              '’’اعتماد جتنا مضبوط ہو، ٹوٹنے پر اتنا ہی زیادہ نقصان کرتا ہے۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 326415),
          end: Duration(milliseconds: 329535),
          text: 'ان کے ساتھ ایک تیسرا سایہ بھی تھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 329535),
          end: Duration(milliseconds: 336495),
          text:
              'وہ مڑا تو اس کے گلے کی کوئی نیلی چیز دیوار کی کھردری کیل سے لمحہ بھر کو اٹکی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 336495),
          end: Duration(milliseconds: 339888),
          text: 'ایک ننھا سا نیلا ریشہ پیچھے رہ گیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 339888),
          end: Duration(milliseconds: 342368),
          text: 'آج کا چیلنج: افواہ روکیں',
        ),
        CaptionLine(
          start: Duration(milliseconds: 342368),
          end: Duration(milliseconds: 350063),
          text:
              'آج اگر کسی کے بارے میں کوئی ایسی بات سنیں جس کی تصدیق نہ ہوئی ہو تو اسے آگے مت پھیلائیں۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 350063),
          end: Duration(milliseconds: 352183),
          text: 'اگر کوئی پوچھے تو کہیں:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 352183),
          end: Duration(milliseconds: 353663),
          text: '’’مجھے معلوم نہیں۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 353663),
          end: Duration(milliseconds: 355303),
          text: 'ایک قدم آگے',
        ),
        CaptionLine(
          start: Duration(milliseconds: 355303),
          end: Duration(milliseconds: 362343),
          text:
              'اگر آپ پہلے ہی کوئی غیر مصدقہ بات کسی کو بتا چکے ہیں تو واپس جا کر اپنی بات درست کریں۔',
        ),
      ],
    ),
    Story(
      id: 'honesty_ur_03',
      title: 'قسط 3 · نیلا دھاگا',
      narrator: 'Imaan & Akhlaq',
      coverAsset: 'assets/covers/honesty.webp',
      audioAsset: 'assets/audio/ur/honesty/03.ogg',
      category: StoryCategory.moral,
      description: 'کتابِ امانت — قسط 3 از 4',
      captions: [
        CaptionLine(
          start: Duration(milliseconds: 0),
          end: Duration(milliseconds: 1265),
          text: 'باب سوم',
        ),
        CaptionLine(
          start: Duration(milliseconds: 1265),
          end: Duration(milliseconds: 2585),
          text: 'نیلا دھاگا',
        ),
        CaptionLine(
          start: Duration(milliseconds: 2585),
          end: Duration(milliseconds: 10013),
          text:
              'اخلاقی سبق: سچائی صرف جھوٹ نہ بولنے کا نام نہیں، مکمل اور درست بات کہنا بھی سچائی ہے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 10013),
          end: Duration(milliseconds: 15213),
          text:
              'ناشتے سے پہلے ہی نیلا دھاگا اکیڈمی کا پسندیدہ موضوع بن چکا تھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 15213),
          end: Duration(milliseconds: 20913),
          text:
              'پہلا سبق شروع ہونے تک کچھ بچے اسے ’’طارق کے بیگ کا دھاگا‘‘ کہنے لگے تھے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 20913),
          end: Duration(milliseconds: 23465),
          text: 'حالانکہ یہ بات کسی نے ثابت نہیں کی تھی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 23841),
          end: Duration(milliseconds: 27161),
          text: 'شیخ انکل نے تختے پر دو جملے لکھے:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 27161),
          end: Duration(milliseconds: 28961),
          text: 'دھاگا نیلا ہے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 28961),
          end: Duration(milliseconds: 31561),
          text: 'دھاگا طارق کے بیگ سے آیا ہے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 31561),
          end: Duration(milliseconds: 32961),
          text: 'انہوں نے پوچھا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 33711),
          end: Duration(milliseconds: 35961),
          text: '’’ان میں سے حقیقت کون سی ہے؟‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 35961),
          end: Duration(milliseconds: 37595),
          text: 'کلاس نے کہا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 37595),
          end: Duration(milliseconds: 38321),
          text: '’’پہلی۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 38321),
          end: Duration(milliseconds: 39601),
          text: '’’اور دوسری؟‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 39601),
          end: Duration(milliseconds: 41201),
          text: 'ایمان نے جواب دیا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 41201),
          end: Duration(milliseconds: 42721),
          text: '’’ایک امکان۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 42721),
          end: Duration(milliseconds: 43721),
          text: '’’بالکل۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 43809),
          end: Duration(milliseconds: 51049),
          text:
              'کبھی کبھی ہم جھوٹ نہیں بولتے، مگر کسی امکان کو ایسے بیان کر دیتے ہیں جیسے وہ حقیقت ہو۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 51049),
          end: Duration(milliseconds: 53609),
          text: 'یہ بھی سچائی کے خلاف جا سکتا ہے۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 54045),
          end: Duration(milliseconds: 57529),
          text: 'کلاس کے بعد شیخ انکل نے طارق کو دفتر میں بلایا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 57995),
          end: Duration(milliseconds: 61369),
          text: '’’طارق، تم نے کہا تھا تم نے کتابِ امانت نہیں لی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 61369),
          end: Duration(milliseconds: 66177),
          text: 'میرے پاس تمہاری اس بات کو غلط ثابت کرنے والا کوئی ثبوت نہیں۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 66177),
          end: Duration(milliseconds: 67777),
          text: 'لیکن ایک الگ سوال ہے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 67777),
          end: Duration(milliseconds: 72137),
          text:
              'کیا تم پہلے کبھی دوپہر کے وقفے میں میرے دفتر کے قریب آئے ہو؟‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 72600),
          end: Duration(milliseconds: 74337),
          text: 'طارق نے فرش کی طرف دیکھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 74337),
          end: Duration(milliseconds: 76071),
          text: 'کچھ دیر خاموش رہا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 76071),
          end: Duration(milliseconds: 76937),
          text: 'پھر بولا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 76937),
          end: Duration(milliseconds: 77484),
          text: '’’جی۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 77484),
          end: Duration(milliseconds: 78577),
          text: '’’کیوں؟‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 79048),
          end: Duration(milliseconds: 80577),
          text: 'طارق نے گہرا سانس لیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 80577),
          end: Duration(milliseconds: 83745),
          text: '’’ایک ہفتہ پہلے میں راہداری میں دوڑ رہا تھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 83745),
          end: Duration(milliseconds: 86765),
          text: 'دفتر کے پاس رکھا گملہ مجھ سے ٹکرا گیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 86765),
          end: Duration(milliseconds: 88535),
          text: 'اس کے نیچے دراڑ پڑ گئی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 88535),
          end: Duration(milliseconds: 90305),
          text: 'کسی نے نہیں دیکھا تھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 90305),
          end: Duration(milliseconds: 91314),
          text: 'میں ڈر گیا۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 91314),
          end: Duration(milliseconds: 93585),
          text: 'اس کی آواز دھیمی ہو گئی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 93585),
          end: Duration(milliseconds: 96465),
          text: '’’میں وقفے میں واپس آ کر اسے دیکھتا تھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 96465),
          end: Duration(milliseconds: 100905),
          text: 'میں اپنی جیب خرچ بھی جمع کر رہا تھا تاکہ نیا گملہ لے سکوں۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 100905),
          end: Duration(milliseconds: 102345),
          text: 'وہ جلدی سے بولا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 102345),
          end: Duration(milliseconds: 103508),
          text: '’’میں نے کتاب نہیں لی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 103713),
          end: Duration(milliseconds: 107033),
          text: 'لیکن مجھے گملے کے بارے میں پہلے بتا دینا چاہیے تھا۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 107033),
          end: Duration(milliseconds: 108936),
          text: 'شیخ انکل نے گملہ دیکھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 108936),
          end: Duration(milliseconds: 112953),
          text: 'واقعی نیچے وہی دراڑ تھی جس کا طارق نے ذکر کیا تھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 112953),
          end: Duration(milliseconds: 114273),
          text: 'انہوں نے کہا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 114273),
          end: Duration(milliseconds: 116273),
          text: '’’مکمل سچ بتانے کا شکریہ۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 116273),
          end: Duration(milliseconds: 124411),
          text:
              'گملے کے بارے میں خاموش رہنے سے تم نے لوگوں کے لیے الجھن پیدا کی، لیکن ایک غلطی دوسری تہمت کو سچا نہیں بنا دیتی۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 125563),
          end: Duration(milliseconds: 126301),
          text: 'طارق نے پوچھا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 126301),
          end: Duration(milliseconds: 127821),
          text: '’’کیا مجھے سزا ملے گی؟‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 127821),
          end: Duration(milliseconds: 131901),
          text: '’’تم گملہ بدلنے میں مدد کرو گے، کیونکہ نقصان تم سے ہوا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 131901),
          end: Duration(milliseconds: 134301),
          text: 'یہ ذمہ داری ہے، انتقام نہیں۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 134728),
          end: Duration(milliseconds: 137181),
          text: 'طارق نے کئی دن بعد سکون کا سانس لیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 137181),
          end: Duration(milliseconds: 141061),
          text: 'جب اس نے ایمان اور اخلاق کو بتایا تو اخلاق نے کہا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 141061),
          end: Duration(milliseconds: 145649),
          text:
              '’’تو آپ واقعی کچھ چھپا رہے تھے، لیکن وہ چیز نہیں جس کا سب کو شک تھا۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 145649),
          end: Duration(milliseconds: 145889),
          text: '’’جی۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 145889),
          end: Duration(milliseconds: 148649),
          text: 'ایمان نے اپنی نوٹ بک میں لکھا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 149286),
          end: Duration(milliseconds: 151649),
          text: 'گھبراہٹ کی ایک سے زیادہ وجوہات ہو سکتی ہیں۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 151649),
          end: Duration(milliseconds: 155649),
          text: 'اس دوپہر انہوں نے اجازت لے کر نیلے دھاگے کو دوبارہ دیکھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 155649),
          end: Duration(milliseconds: 159649),
          text: 'ایمان نے اسے طارق کے بیگ کے ریشوں کے قریب رکھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 159649),
          end: Duration(milliseconds: 160649),
          text: '’’یہ ایک جیسے نہیں۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 160649),
          end: Duration(milliseconds: 162649),
          text: 'اخلاق نے غور سے دیکھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 163049),
          end: Duration(milliseconds: 163249),
          text: '’’طارق کے بیگ کا دھاگا موٹا ہے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 163617),
          end: Duration(milliseconds: 166464),
          text: 'سراغ والا چپٹا اور چمکدار ہے۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 166464),
          end: Duration(milliseconds: 167825),
          text: '’’کسی فیتے جیسا۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 167825),
          end: Duration(milliseconds: 169311),
          text: '’’یا لانیارڈ جیسا۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 169311),
          end: Duration(milliseconds: 171415),
          text: 'انہوں نے کلاس میں نظر دوڑائی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 172157),
          end: Duration(milliseconds: 174916),
          text: 'کئی بچوں کے گلے میں نیلے لانیارڈ تھے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 174916),
          end: Duration(milliseconds: 176690),
          text: 'سراغ اب زیادہ مفید تھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 176690),
          end: Duration(milliseconds: 180237),
          text: 'لیکن ابھی کسی شخص کا نام لینے کے لیے کافی نہیں۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 180851),
          end: Duration(milliseconds: 182077),
          text: 'وسیم قریب سے گزرا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 182077),
          end: Duration(milliseconds: 183585),
          text: '’’تحقیق اب بھی چل رہی ہے؟‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 183585),
          end: Duration(milliseconds: 185141),
          text: 'ایمان نے کہا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 185141),
          end: Duration(milliseconds: 187785),
          text: '’’صرف حقائق لکھ رہے ہیں۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 188250),
          end: Duration(milliseconds: 190665),
          text: 'وسیم نے طارق کا بیگ بند کرنے میں مدد کی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 190665),
          end: Duration(milliseconds: 194203),
          text: 'اسی دوران اس کا اپنا نیلا لانیارڈ میز کے کنارے سے رگڑا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 194585),
          end: Duration(milliseconds: 198585),
          text: 'اخلاق نے دیکھا کہ ایک کنارہ کچھ اکھڑا ہوا تھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 198585),
          end: Duration(milliseconds: 200585),
          text: 'وہ کچھ کہنے لگا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 200585),
          end: Duration(milliseconds: 203553),
          text: 'ایمان نے اپنی نوٹ بک پر انگلی رکھ دی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 203553),
          end: Duration(milliseconds: 206688),
          text: 'اخلاق نے لکھے ہوئے الفاظ دیکھے:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 206688),
          end: Duration(milliseconds: 208193),
          text: 'کافی ثبوت نہیں۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 208193),
          end: Duration(milliseconds: 210113),
          text: 'اس نے منہ بند کر لیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 210113),
          end: Duration(milliseconds: 213113),
          text: 'اسی دن دو سیکیورٹی اہلکار آئے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 213113),
          end: Duration(milliseconds: 218193),
          text: 'انہوں نے دفتر کی راہداری کے اوپر ایک چھوٹا سیاہ آلہ نصب کیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 218193),
          end: Duration(milliseconds: 219945),
          text: 'شہزیب نے پوچھا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 219945),
          end: Duration(milliseconds: 220528),
          text: '’’خفیہ روبوٹ؟‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 221258),
          end: Duration(milliseconds: 223009),
          text: 'شیخ انکل نے کہا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 223009),
          end: Duration(milliseconds: 223521),
          text: '’’نہیں۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 223521),
          end: Duration(milliseconds: 224940),
          text: 'اخلاق نے پوچھا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 224940),
          end: Duration(milliseconds: 227186),
          text: '’’ہوم ورک پکڑنے والی مشین؟‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 227186),
          end: Duration(milliseconds: 228250),
          text: '’’وہ بھی نہیں۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 228250),
          end: Duration(milliseconds: 228841),
          text: '’’تو پھر؟‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 229573),
          end: Duration(milliseconds: 232081),
          text: '’’اکیڈمی کی حفاظت میں مدد دینے والی چیز۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 232081),
          end: Duration(milliseconds: 234801),
          text: 'زیادہ تر بچے جلد ہی بھول گئے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 234801),
          end: Duration(milliseconds: 236321),
          text: 'ایمان نہیں بھولی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 236321),
          end: Duration(milliseconds: 241641),
          text: 'دن کے اختتام پر وہی سفید نوٹ شیخ انکل کی دراز میں محفوظ تھا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 241641),
          end: Duration(milliseconds: 244819),
          text: '’’سچ اپنے قدموں کے نشان چھوڑتا ہے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 244819),
          end: Duration(milliseconds: 246149),
          text: 'ان کا پیچھا کرو۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 246149),
          end: Duration(milliseconds: 248809),
          text: 'اب بچوں نے ایک نئی بات سیکھی تھی:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 248809),
          end: Duration(milliseconds: 252109),
          text: 'قدموں کے نشان ہمیں دروازے تک لے جا سکتے ہیں۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 252109),
          end: Duration(milliseconds: 255909),
          text: 'مگر یہ خود نہیں بتاتے کہ دروازہ کس نے کھولا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 255909),
          end: Duration(milliseconds: 259029),
          text: 'آج کا چیلنج: مکمل سچ بولیں',
        ),
        CaptionLine(
          start: Duration(milliseconds: 259029),
          end: Duration(milliseconds: 265082),
          text:
              'ایسی کوئی بات یاد کریں جس میں آپ نے سچ تو کہا، مگر اہم حصہ چھوڑ دیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 265082),
          end: Duration(milliseconds: 266457),
          text: 'اسے مکمل کریں۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 266457),
          end: Duration(milliseconds: 267476),
          text: 'ایک قدم آگے',
        ),
        CaptionLine(
          start: Duration(milliseconds: 267476),
          end: Duration(milliseconds: 275979),
          text:
              'اگر ادھوری بات کی وجہ سے کسی کو نقصان یا غلط فہمی ہوئی ہے تو اسے درست کرنے کے لیے عملی قدم بھی اٹھائیں۔',
        ),
      ],
    ),
    Story(
      id: 'honesty_ur_04',
      title: 'قسط 4 · اعتماد کا امتحان',
      narrator: 'Imaan & Akhlaq',
      coverAsset: 'assets/covers/honesty.webp',
      audioAsset: 'assets/audio/ur/honesty/04.ogg',
      category: StoryCategory.moral,
      description: 'کتابِ امانت — قسط 4 از 4',
      captions: [
        CaptionLine(
          start: Duration(milliseconds: 479),
          end: Duration(milliseconds: 1621),
          text: 'باب چہارم',
        ),
        CaptionLine(
          start: Duration(milliseconds: 2336),
          end: Duration(milliseconds: 3479),
          text: 'اعتماد کا امتحان',
        ),
        CaptionLine(
          start: Duration(milliseconds: 3479),
          end: Duration(milliseconds: 6949),
          text:
              'اخلاقی سبق: امانت کی حفاظت کی جاتی ہے، اس کا دکھاوا نہیں کیا جاتا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 7447),
          end: Duration(milliseconds: 13953),
          text:
              'دو دن بعد اسلامیات کی استاد ایک چھوٹا لکڑی کا عطیہ باکس کلاس میں لائیں۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 14766),
          end: Duration(milliseconds: 19806),
          text:
              'اکیڈمی کی خیراتی مہم میں مختلف خاندانوں کے لیے رقم جمع ہوئی تھی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 19807),
          end: Duration(milliseconds: 21013),
          text: 'انہوں نے کہا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 21013),
          end: Duration(milliseconds: 22099),
          text: '’’یہ امانت ہے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 22099),
          end: Duration(milliseconds: 24029),
          text: 'یہ ہماری ملکیت نہیں۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 24029),
          end: Duration(milliseconds: 27167),
          text: 'اس لیے اسے پوری حفاظت سے رکھنا ہے۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 27847),
          end: Duration(milliseconds: 28496),
          text: 'باکس بند ہوا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 28496),
          end: Duration(milliseconds: 31415),
          text: 'چابی الماری کے پاس محفوظ رکھی گئی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 31415),
          end: Duration(milliseconds: 36214),
          text:
              'بعد میں وسیم سے کہا گیا کہ وہ باکس دفتر تک پہنچانے میں مدد کرے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 36215),
          end: Duration(milliseconds: 38215),
          text: 'شہزیب نے اعلان کیا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 38800),
          end: Duration(milliseconds: 43015),
          text: '’’وسیم اب اکیڈمی کا سرکاری قابلِ اعتماد شخص بن چکا ہے۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 43015),
          end: Duration(milliseconds: 43948),
          text: 'وسیم ہنسا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 43948),
          end: Duration(milliseconds: 47214),
          text: '’’میرے لیے الگ یونیفارم مت بنوا دینا۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 47383),
          end: Duration(milliseconds: 50743),
          text: 'ایک گھنٹے بعد استاد نے الماری کھولنا چاہی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 50743),
          end: Duration(milliseconds: 52243),
          text: 'چابی غائب تھی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 52243),
          end: Duration(milliseconds: 54203),
          text: 'کلاس میں تناؤ پھیل گیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 54203),
          end: Duration(milliseconds: 56470),
          text: 'چند نظریں فوراً طارق کی طرف اٹھیں۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 57343),
          end: Duration(milliseconds: 58723),
          text: 'طارق نے محسوس کر لیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 58723),
          end: Duration(milliseconds: 60642),
          text: 'ایمان بھی دیکھ رہی تھی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 60643),
          end: Duration(milliseconds: 62043),
          text: 'اس کے دل میں آیا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 62043),
          end: Duration(milliseconds: 63922),
          text: 'اسے دیکھنا بند کرو۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 63923),
          end: Duration(milliseconds: 66682),
          text: 'مگر پھر اسے اپنا اصول یاد آیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 66683),
          end: Duration(milliseconds: 67991),
          text: 'پہلے حقائق۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 67991),
          end: Duration(milliseconds: 69910),
          text: 'سب نے تلاش شروع کی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 69910),
          end: Duration(milliseconds: 73191),
          text: 'شہزیب کو کھڑکی کے پاس ایک چھوٹی چابی ملی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 73191),
          end: Duration(milliseconds: 76270),
          text: 'اس نے اسے فاتحانہ انداز میں بلند کیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 76271),
          end: Duration(milliseconds: 77060),
          text: '’’راز حل!‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 77849),
          end: Duration(milliseconds: 79270),
          text: 'وسیم نے فوراً کہا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 79271),
          end: Duration(milliseconds: 81625),
          text: '’’یہ عطیہ باکس کی چابی نہیں۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 81625),
          end: Duration(milliseconds: 83390),
          text: 'اس پر سرخ نشان تھا۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 83934),
          end: Duration(milliseconds: 85130),
          text: 'استاد نے چابی دیکھی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 85130),
          end: Duration(milliseconds: 86871),
          text: 'وہ درست کہہ رہا تھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 86871),
          end: Duration(milliseconds: 87630),
          text: 'دوبارہ تلاش ہوئی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 87769),
          end: Duration(milliseconds: 91518),
          text: 'اصل چابی استاد کی کرسی کے نیچے ملی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 91519),
          end: Duration(milliseconds: 94118),
          text: 'شاید الماری کھولتے وقت گر گئی تھی۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 94119),
          end: Duration(milliseconds: 96399),
          text: 'سب نے سکون کا سانس لیا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 97059),
          end: Duration(milliseconds: 98599),
          text: 'شیخ انکل نے کمرے میں دیکھا۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 98599),
          end: Duration(milliseconds: 100319),
          text: '’’ابھی کیا ہونے والا تھا؟',
        ),
        CaptionLine(
          start: Duration(milliseconds: 100319),
          end: Duration(milliseconds: 106198),
          text:
              'ایک چابی نہ ملی اور ہم میں سے کچھ لوگ فوراً اسے پہلے سے مشتبہ شخص سے جوڑنے لگے۔',
        ),
        CaptionLine(
          start: Duration(milliseconds: 106198),
          end: Duration(milliseconds: 109254),
          text: 'لیکن چابی چوری ہوئی ہی نہیں تھی۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 109254),
          end: Duration(milliseconds: 110759),
          text: 'انہوں نے صاف کہا:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 110759),
          end: Duration(milliseconds: 115762),
          text: '’’ہر گم شدہ چیز جرم نہیں ہوتی، اور ہر اتفاق سراغ نہیں ہوتا۔‘‘',
        ),
        CaptionLine(
          start: Duration(milliseconds: 115762),
          end: Duration(milliseconds: 118447),
          text: 'ایمان نے فوراً یہ جملہ لکھ لیا۔',
        ),
      ],
    ),
  ],
);
