// GENERATED by tools/gen_series.dart from tools/series/salih_en.json.
// Do not edit by hand: change the config or script and rerun.
//
// Caption times come from aligning the script to a whisper
// transcript of the recording.

import '../series.dart';
import '../story.dart';
import '../story_category.dart';

const Series salihEnglish = Series(
  id: 'salih_en',
  title: 'Hazrat Salih (A.S.)',
  language: StoryLanguage.english,
  category: StoryCategory.prophets,
  coverAsset: 'assets/covers/salih.webp',
  description: 'A 5-part story about boundaries, rights and responsibility.',
  trailer: Story(
    id: 'salih_en_00',
    title: 'Trailer · Hazrat Salih (A.S.)',
    narrator: 'Imaan & Akhlaq',
    coverAsset: 'assets/covers/salih.webp',
    audioAsset: 'assets/audio/en/salih/00_trailer.ogg',
    category: StoryCategory.prophets,
    description: 'Meet the story: Hazrat Salih (A.S.) in under a minute.',
    captions: [
      CaptionLine(
        start: Duration(milliseconds: 0),
        end: Duration(milliseconds: 4373),
        text: 'IMAAN & AKHLAQ',
      ),
      CaptionLine(
        start: Duration(milliseconds: 4373),
        end: Duration(milliseconds: 5840),
        text: 'Hazrat Salih (A.S.) Story Series',
      ),
      CaptionLine(
        start: Duration(milliseconds: 6340),
        end: Duration(milliseconds: 11440),
        text:
            'Five Connected Episodes on Boundaries, Rights and Responsibility',
      ),
      CaptionLine(
        start: Duration(milliseconds: 11940),
        end: Duration(milliseconds: 15340),
        text: 'Episode 1: Why Is Everything a Rule?',
      ),
      CaptionLine(
        start: Duration(milliseconds: 15840),
        end: Duration(milliseconds: 18640),
        text: 'Episode 2: But Tell Me Why',
      ),
      CaptionLine(
        start: Duration(milliseconds: 19140),
        end: Duration(milliseconds: 22527),
        text: 'Episode 3: That Was My Turn',
      ),
      CaptionLine(
        start: Duration(milliseconds: 22527),
        end: Duration(milliseconds: 26447),
        text: 'Episode 4: Ammi Will Never Know',
      ),
      CaptionLine(
        start: Duration(milliseconds: 26447),
        end: Duration(milliseconds: 29716),
        text: 'Episode 5: The Rule Was Not the Enemy',
      ),
    ],
  ),
  episodes: [
    Story(
      id: 'salih_en_01',
      title: 'Ep 1 · Why Is Everything a Rule?',
      narrator: 'Imaan & Akhlaq',
      coverAsset: 'assets/covers/salih.webp',
      audioAsset: 'assets/audio/en/salih/01_why_is_everything_a_rule.ogg',
      category: StoryCategory.prophets,
      description: 'Hazrat Salih (A.S.) — episode 1 of 5.',
      captions: [
        CaptionLine(
          start: Duration(milliseconds: 731),
          end: Duration(milliseconds: 4171),
          text: 'Episode 1: Why Is Everything a Rule?',
        ),
        CaptionLine(
          start: Duration(milliseconds: 4171),
          end: Duration(milliseconds: 29219),
          text:
              'The first morning of the summer holidays should have felt completely free. There was no school bell, no uniform and no homework waiting. Mohsin and Mohsina had come over early to spend the day with Imaan and Akhlaq, and the four children were already planning football, a movie, cold drinks and, if the afternoon became hot enough, a water game in the garden.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 30465),
          end: Duration(milliseconds: 70155),
          text:
              'Akhlaq walked into the kitchen expecting breakfast and stopped in front of the refrigerator. A large sheet of paper had been fixed to the door. At the top, Ammi had written: OUR HOLIDAY HOME PLAN. Underneath were a few simple rules. Screen time would come after basic responsibilities. Special snacks had to be asked for before taking them. Everyone would get a fair turn with shared things. The reserve water was not to be used for games. Nobody would leave the house without telling an adult. And between two and four in the afternoon, the house had to stay reasonably quiet because Dadi Jaan rested then.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 70815),
          end: Duration(milliseconds: 99541),
          text:
              'Akhlaq read the list twice and turned towards his mother. “Ammi, is this a holiday plan or a list of things we are not allowed to do?” Mohsin came closer and immediately noticed the line about reserve water. “No water game?” he asked. Akhlaq pointed at the paper as though Mohsin had proved his case. “Exactly. We are only on the first morning. At this rate, by August we will need another refrigerator.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 100351),
          end: Duration(milliseconds: 115339),
          text:
              'Ammi placed breakfast on the table and smiled. “You may complain after you eat.” Akhlaq sat down. “Is complaining also on a schedule?” Ammi replied that he seemed perfectly capable of doing that without one, and everyone laughed.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 130027),
          end: Duration(milliseconds: 132667),
          text:
              'The children played a board game, helped clear the breakfast table and then went outside with a football. By midday, however, the heat had become uncomfortable. Mohsin wiped his forehead and looked towards the garden hose. Akhlaq followed his eyes. No words were needed.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 132667),
          end: Duration(milliseconds: 156635),
          text:
              '“A water match,” Akhlaq said. Imaan immediately remembered the chart. “Ammi said no reserve water for games.” Akhlaq frowned. “The chart says reserve water. Maybe the garden hose uses normal water.” Mohsina smiled. “You are not asking a question. You are searching for an escape.” “I am seeking clarification.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 156635),
          end: Duration(milliseconds: 175643),
          text:
              'They found Abbu in the sitting room. Akhlaq asked, in his most respectful voice, whether they could use the garden hose for ten minutes. Abbu asked what for. When Akhlaq explained, he shook his head. “Not today. The water supply has been irregular this week. Part of the rooftop tank is being kept as reserve.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 176003),
          end: Duration(milliseconds: 196375),
          text:
              '“But there is so much water in the tank,” Akhlaq replied. Abbu looked at him. “Have you checked?” “No.” “Then how do you know?” “Because it is a large tank.” Abbu smiled slightly. “Large things can also become empty. For now, no water games.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 196931),
          end: Duration(milliseconds: 224899),
          text:
              'The children walked back towards the garden. Mohsin whispered that parents had a very close relationship with the word no. Akhlaq agreed. Imaan reminded them that Abbu had explained the reason, but Akhlaq still looked dissatisfied. “We only wanted ten minutes.” Mohsina sat on the garden step. “We keep calling everything we want ‘only a little’. Maybe that is why adults keep answering.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 224899),
          end: Duration(milliseconds: 250638),
          text:
              'Later that afternoon, another rule became inconvenient. The children wanted to watch an adventure film in the sitting room, but it was almost two o’clock. Ammi reminded them that Dadi Jaan would be resting. Mohsin promised to keep the volume low, but Dadi Jaan smiled from the doorway and said, “Your definition of low and mine are not always the same.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 250906),
          end: Duration(milliseconds: 272772),
          text:
              'Abbu allowed them to watch in Akhlaq’s room as long as the volume remained reasonable. As they carried the laptop upstairs, Akhlaq muttered, “Another restriction.” This time Imaan stopped him. “You know why Dadi needs rest.” “I know.” “Then why are you talking as if Ammi made the rule just to stop us having fun?”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 273421),
          end: Duration(milliseconds: 293691),
          text:
              'Akhlaq took a moment before answering. “Because sometimes it feels like every time we want something, somebody older decides whether we are allowed to have it.” Mohsin nodded. “Exactly.” Mohsina leaned against the wall. “Maybe adults forget that children also want to decide things.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 293933),
          end: Duration(milliseconds: 322739),
          text:
              'Abbu had been passing the staircase and heard the last sentence. He stopped and said, “That is probably true sometimes.” “You agree?” Akhlaq asked. “I agree that children need chances to make decisions,” Abbu replied. “But does making decisions mean having no boundaries?” Akhlaq answered no. “Then perhaps the better question is not, ‘Why are there rules?’ but, ‘What is this rule protecting?’”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 323025),
          end: Duration(milliseconds: 347707),
          text:
              'Abbu sat on the top step and explained that adults could be unclear, impatient or even mistaken. Being older did not make a person right about everything. Children could respectfully ask why a rule existed. But asking why to understand was different from asking why only because they hoped the answer would give them permission to do what they already wanted.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 349675),
          end: Duration(milliseconds: 369675),
          text:
              'Akhlaq smiled. “So asking why is allowed.” “Yes.” “And if I do not like the answer?” “You may still dislike it,” Abbu said. “Disagreement does not automatically cancel a reasonable boundary.” Mohsina laughed softly. “That is the part he was hoping you would not say.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 369974),
          end: Duration(milliseconds: 398131),
          text:
              'Abbu then asked them to imagine a hot pan on the stove. If a parent told a small child not to touch it, the danger would still be real even if the child did not yet understand heat properly. Sometimes a reason could be understood immediately. Sometimes it needed explanation. And sometimes a responsible adult knew something the child had not yet seen. “Like the water tank?” Imaan asked. “Exactly.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 398393),
          end: Duration(milliseconds: 412739),
          text:
              'Abbu then asked, “Do you remember which Prophet comes after Hud, peace be upon him, in the stories you have been learning?” “Salih, peace be upon him,” Imaan answered. “And his people were Thamud,” Mohsin added.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 414848),
          end: Duration(milliseconds: 433147),
          text:
              'Abbu nodded. He explained that Allah had given Thamud great abilities and blessings. The Qur’an describes how they settled in the land, built in its plains and carved homes into the mountains. Allah sent Salih (A.S.) from among them, calling them to worship Allah alone.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 433147),
          end: Duration(milliseconds: 456515),
          text:
              '“Were they wrong because they were successful?” Mohsina asked. “No,” Abbu replied. “Just as strength was not the problem with ‘Ad, ability itself was not the problem with Thamud. A deeper problem appears in their story: what happens when people do not want to accept that freedom has limits before Allah.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 456911),
          end: Duration(milliseconds: 485144),
          text:
              'Akhlaq looked back towards the refrigerator chart downstairs. “I knew the rules were going to enter the Prophet story somehow.” Abbu smiled. “Human family rules and Allah’s commands are not the same thing. Human rules can be mistaken and can be discussed. But Salih’s story can still teach us something about boundaries, rights and the danger of knowingly crossing a limit simply because we do not like being restricted.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 485776),
          end: Duration(milliseconds: 513819),
          text:
              'Then he asked them a question. “If you can do something, does that automatically mean you have the right to do it?” Imaan said she could open Mohsina’s bag, but that did not make it her right. Mohsina said Akhlaq could eat all the dessert, but that did not make it fair. Akhlaq protested that he was always the food example. Mohsin said he could turn the television volume high while Dadi slept, but his enjoyment would interfere with her rest.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 515472),
          end: Duration(milliseconds: 537987),
          text:
              'Abbu nodded. “Exactly. Ability and permission are not the same thing.” Akhlaq looked towards the garden hose. “And I can open the tap, but that does not mean I have the right to use the water however I want.” “Now you are reaching the point,” Abbu said. Akhlaq sighed. “I do not enjoy reaching points that reduce my options.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 537987),
          end: Duration(milliseconds: 557684),
          text:
              'As they returned downstairs, Akhlaq stopped again in front of the refrigerator and read the line: DO NOT USE THE RESERVE WATER. This time he did not complain immediately. Instead, he turned towards Abbu. “I still want to know exactly how much water is there.” Abbu smiled. “Good.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 557684),
          end: Duration(milliseconds: 583723),
          text:
              '“Good?” “You are asking to understand, not asking for permission to ignore the answer.” “So you will show us?” “Tomorrow morning.” Akhlaq folded his arms. “If there is loads of water, I would like the rule reviewed.” “And if there is not?” Abbu asked. Akhlaq hesitated. “Then perhaps I will review my complaint.” Mohsina smiled. “That sounds fair.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 584723),
          end: Duration(milliseconds: 607491),
          text:
              'Abbu looked at the chart once more. “You will find something similar in the story of Salih (A.S.). There comes a point when a boundary becomes very clear. Then the question is no longer whether people understood it.” “What is the question?” Mohsin asked. Abbu answered quietly, “What did they do after they understood?”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 607491),
          end: Duration(milliseconds: 619099),
          text:
              'For the first time, the holiday rules did not look to Akhlaq like a wall built around his freedom. Perhaps some of them were protecting things he had not noticed yet. Tomorrow, he intended to find out.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 619099),
          end: Duration(milliseconds: 629227),
          text: 'Challenge of the Day: Can I Do It, or Do I Have the Right?',
        ),
        CaptionLine(
          start: Duration(milliseconds: 629227),
          end: Duration(milliseconds: 634927),
          text:
              'Today, notice one moment when you can do something but should first ask whether you have the right to do it.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 634927),
          end: Duration(milliseconds: 641707),
          text:
              'Before acting, ask: “Just because I can do this, does it mean I should?”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 643827),
          end: Duration(milliseconds: 646027),
          text: 'Level-Up',
        ),
        CaptionLine(
          start: Duration(milliseconds: 646027),
          end: Duration(milliseconds: 669175),
          text:
              'Choose one family rule you do not fully understand. Instead of complaining or secretly breaking it, respectfully ask: “Can you explain what this rule is protecting?” Then listen carefully before deciding what you think.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 669175),
          end: Duration(milliseconds: 669176),
          text: 'Next Episode: But Tell Me Why',
        ),
      ],
    ),
    Story(
      id: 'salih_en_02',
      title: 'Ep 2 · But Tell Me Why',
      narrator: 'Imaan & Akhlaq',
      coverAsset: 'assets/covers/salih.webp',
      audioAsset: 'assets/audio/en/salih/02_but_tell_me_why.ogg',
      category: StoryCategory.prophets,
      description: 'Hazrat Salih (A.S.) — episode 2 of 5.',
      captions: [
        CaptionLine(
          start: Duration(milliseconds: 4177),
          end: Duration(milliseconds: 4323),
          text: 'Episode 2: But Tell Me Why',
        ),
        CaptionLine(
          start: Duration(milliseconds: 4323),
          end: Duration(milliseconds: 22499),
          text:
              'The next morning, Akhlaq was awake earlier than everyone expected. By seven-thirty he was already waiting near the staircase that led to the rooftop. Mohsin rubbed his eyes and asked, “You wake up this early for water?” Akhlaq replied, “For evidence. Abbu promised to show us the tank.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 22782),
          end: Duration(milliseconds: 38304),
          text:
              'Imaan smiled and called Abbu, who joined them a few minutes later. Before they went upstairs, he handed Imaan a small notebook. Akhlaq looked suspicious. “Are we studying during the holidays?” Abbu shook his head. “No. You are going to calculate.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 38304),
          end: Duration(milliseconds: 62415),
          text:
              'They climbed to the rooftop. The morning air was already warm. Abbu led them towards the large water tank and opened the small inspection lid. The children leaned forward carefully while he held it. “There,” he said. “What do you see?” Akhlaq looked inside. “Water.” Mohsin laughed. “Excellent observation.” Akhlaq added that there was still quite a lot.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 62557),
          end: Duration(milliseconds: 81603),
          text:
              'Abbu nodded and showed them a coloured mark on the outside of the tank. He explained that the family tried not to let the water fall below that level unless necessary. The water above the line was the amount they could normally use while waiting for the next supply. The amount below it was kept as reserve.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 82523),
          end: Duration(milliseconds: 112699),
          text:
              'Akhlaq frowned. “But why keep so much?” Abbu smiled. “Good question. Let us find out.” He asked Imaan to write down the family’s basic uses of water. They listed drinking, cooking, washing dishes, bathing, cleaning, laundry, Dadi Jaan’s needs and water for the plants. Then Abbu asked them to imagine that the next supply was delayed by two days. Mohsin looked at the list. “That is a lot of water.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 112948),
          end: Duration(milliseconds: 137925),
          text:
              'Abbu handed Akhlaq a bucket and asked him to fill it from the hose for ten seconds. The bucket filled much faster than he expected. Mohsina smiled. “Your ten-minute game has become less innocent.” Abbu explained that hose use varied with water pressure, but it could consume far more than the children had imagined. That was why reserve water was not for play while supply was uncertain.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 138262),
          end: Duration(milliseconds: 170603),
          text:
              'Imaan looked at the coloured line again. “Yesterday it looked like extra water.” Mohsina nodded. “Because yesterday we did not know what it was being saved for.” Akhlaq remained quiet for a moment, then admitted that the rule made more sense now. Abbu smiled. Akhlaq added that he still thought Abbu should have shown them the previous day. Abbu agreed that when there was time, explanation could help, though sometimes an adult had to give a quick instruction first.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 170603),
          end: Duration(milliseconds: 188831),
          text:
              'At breakfast, Ammi asked what they had discovered. Akhlaq admitted that he now understood the rule, which was inconvenient because he could no longer pretend it was pointless. Dadi Jaan laughed. “Understanding has ruined many excellent complaints.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 188831),
          end: Duration(milliseconds: 199811),
          text:
              'The chart on the refrigerator was still there, but it looked different now. The rules had not changed. Their knowledge had.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 199811),
          end: Duration(milliseconds: 221939),
          text:
              'Later that afternoon, the children wanted to open a box of special chocolates in the kitchen cupboard. Ammi told them that the box was being saved because guests were expected that evening. Mohsin whispered, “Does the chocolate have a reserve line too?” Ammi heard him. “Yes. It is exactly four children below your reach.” Everyone laughed.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 223667),
          end: Duration(milliseconds: 237407),
          text:
              'This time, however, Akhlaq did not argue. He understood that something could be physically available and still be reserved for a purpose he had not considered.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 237407),
          end: Duration(milliseconds: 253555),
          text:
              'That evening, after Maghrib, Abbu sat with the four children in the family room. Akhlaq had been waiting for the continuation of Salih’s story. “You said yesterday that there came a point when the boundary became very clear,” he reminded him.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 254340),
          end: Duration(milliseconds: 274123),
          text:
              'Abbu nodded. He explained that Salih (A.S.) was sent to the people of Thamud and called them to worship Allah alone. They had been given great abilities and blessings, yet many rejected his message. Then Allah gave them a clear sign connected to a she-camel.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 274123),
          end: Duration(milliseconds: 297571),
          text:
              'Mohsin leaned forward. “Was that the camel that came out of a mountain?” Abbu paused. “You may hear that detail in popular retellings, but for our story we will stay with what the Qur’an clearly tells us. The Qur’an calls her Allah’s she-camel and a sign for them. They were told to leave her to graze in Allah’s land and not harm her.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 297979),
          end: Duration(milliseconds: 315839),
          text:
              'Imaan nodded. “So the important part is that the sign was clear.” “Exactly.” Abbu continued that in another passage, Salih (A.S.) told his people that the she-camel had a share of the water and they had a share on an appointed day.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 316343),
          end: Duration(milliseconds: 339107),
          text:
              'Akhlaq immediately looked towards the refrigerator chart. “Another schedule.” Abbu smiled. “Yes, but remember: this was a command connected to a sign from Allah, not a household rule made by parents.” Mohsina asked whether the people knew what they were supposed to do. Abbu said yes; the boundary was not hidden from them.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 339757),
          end: Duration(milliseconds: 362875),
          text:
              'Mohsin frowned. “Then why would anyone break it?” Abbu explained that people sometimes imagine clear explanation automatically leads to obedience. But human beings can understand something and still dislike it. Akhlaq said that he now understood the water rule but still wanted the game. Abbu agreed: understanding helps, but it does not remove desire.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 363830),
          end: Duration(milliseconds: 371403),
          text:
              'Imaan thought about that. “So the real test comes after the explanation.” “Very often,” Abbu replied.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 371649),
          end: Duration(milliseconds: 391811),
          text:
              'Abbu then asked Akhlaq what his complaint had been before seeing the tank. Akhlaq said he had not understood why they could not use the water. Abbu asked what his complaint was now. Akhlaq admitted that he understood. If he secretly opened the hose that night, he could no longer say nobody had explained it to him.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 392322),
          end: Duration(milliseconds: 415139),
          text:
              'Mohsina said quietly, “Once you know what the boundary protects, crossing it becomes a different kind of choice.” Abbu nodded. He explained that Salih’s people were given a sign, a warning and clear instructions not to harm the she-camel. The problem eventually became not simply lack of information, but deliberate rejection.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 415687),
          end: Duration(milliseconds: 430467),
          text:
              'Mohsin asked whether asking why was wrong. Abbu said no. A sincere question could help a person understand. The danger was when “why?” became a disguise for “I will obey only if I personally approve.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 430673),
          end: Duration(milliseconds: 465283),
          text:
              'Abbu explained that people could keep asking for explanations not because they wanted to understand, but because they hoped eventually to hear an answer that allowed what they already wanted. Imaan smiled. “Like asking Ammi, then Abbu, then Dadi Jaan until someone says yes.” Mohsin looked away. Mohsina laughed and accused him of having done that. Mohsin called it “seeking a second opinion.” Dadi Jaan, passing the room, called out that his second opinion was usually still no. The children burst out laughing.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 483251),
          end: Duration(milliseconds: 503219),
          text:
              'When the room became quiet again, Abbu said that a mature person learned two things together: ask respectfully when genuine understanding was needed, and when a reasonable boundary was clear, do not keep pretending confusion just because obedience was inconvenient.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 503219),
          end: Duration(milliseconds: 505219),
          text:
              'Akhlaq looked towards the kitchen, where the holiday chart was visible. “So the chart is not saying, ‘Never ask questions.’” Abbu agreed. Akhlaq continued, “It is saying, ‘Ask, understand, then take responsibility for what you know.’” Abbu smiled. “Very good.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 505647),
          end: Duration(milliseconds: 534787),
          text:
              'Mohsina asked what happened next with the she-camel. Abbu said that part connected to another family problem they had not had yet. “Turns,” he said. Mohsin groaned. Abbu explained only that the Qur’an mentions an allotted share of water for the she-camel and a share for the people on an appointed day. Akhlaq looked towards Mohsin. Mohsin looked towards the family tablet charging on the side table. Both understood immediately.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 536227),
          end: Duration(milliseconds: 558992),
          text:
              'Before bed, Akhlaq stopped again in front of the refrigerator. He looked at the words: DO NOT USE THE RESERVE WATER. Yesterday, he had seen only a restriction. That morning, he had seen the tank, the line, the bucket and the family’s needs. The words had not changed. But now he knew what they meant.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 558992),
          end: Duration(milliseconds: 571123),
          text:
              'And he was beginning to understand that once a boundary became clear, the next question was no longer whether he liked it. It was what kind of choice he would make after knowing why it was there.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 571123),
          end: Duration(milliseconds: 583091),
          text: 'Challenge of the Day: Ask to Understand',
        ),
        CaptionLine(
          start: Duration(milliseconds: 583091),
          end: Duration(milliseconds: 591300),
          text:
              'Choose one family rule that sometimes frustrates you. Ask your parent or guardian respectfully: “Can you help me understand what this rule is protecting?” Listen to the full answer before replying.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 591300),
          end: Duration(milliseconds: 592073),
          text: 'Level-Up',
        ),
        CaptionLine(
          start: Duration(milliseconds: 592073),
          end: Duration(milliseconds: 602851),
          text:
              'After the reason is explained, ask yourself: “Am I still asking questions because I need understanding, or because I want the answer to change?”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 603059),
          end: Duration(milliseconds: 612499),
          text:
              'Understanding a boundary gives us knowledge. What we do after understanding it shows our character.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 613699),
          end: Duration(milliseconds: 616899),
          text: 'Next Episode: That Was My Turn',
        ),
      ],
    ),
    Story(
      id: 'salih_en_03',
      title: 'Ep 3 · That Was My Turn',
      narrator: 'Imaan & Akhlaq',
      coverAsset: 'assets/covers/salih.webp',
      audioAsset: 'assets/audio/en/salih/03_that_was_my_turn.ogg',
      category: StoryCategory.prophets,
      description: 'Hazrat Salih (A.S.) — episode 3 of 5.',
      captions: [
        CaptionLine(
          start: Duration(milliseconds: 0),
          end: Duration(milliseconds: 2739),
          text: 'Episode 3: That Was My Turn',
        ),
        CaptionLine(
          start: Duration(milliseconds: 3619),
          end: Duration(milliseconds: 28035),
          text:
              'The next morning began peacefully enough. After breakfast, Ammi placed the family tablet on the dining table and reminded the children that they could use it after completing their small morning responsibilities. Because all four wanted it, she divided the available time equally. Imaan would use it first, then Akhlaq, then Mohsina and finally Mohsin. Each child would have thirty minutes.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 28515),
          end: Duration(milliseconds: 43875),
          text:
              'Akhlaq looked at the schedule and smiled. “Another timetable.” Mohsina laughed. “You survived yesterday’s water schedule.” “Barely.” Ammi pointed towards the clock. “Thirty minutes each. When your turn ends, pass it on.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 44164),
          end: Duration(milliseconds: 58723),
          text:
              'Imaan used her time to finish a drawing activity. When the timer rang, she immediately handed the tablet to Akhlaq. “That was fast,” he said. “It was exactly thirty minutes.” “Yes, but emotionally it felt fast.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 59276),
          end: Duration(milliseconds: 77870),
          text:
              'Akhlaq began playing a strategy game. At first he kept checking the clock. After twenty minutes, however, he reached a difficult level. He leaned closer to the screen, completely absorbed. The timer rang. Mohsina looked up from her book. “My turn.” Akhlaq did not move. “One minute.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 78613),
          end: Duration(milliseconds: 98659),
          text:
              'Mohsina waited. A minute passed. Then another. “Akhlaq.” “I’m nearly finished.” “You said one minute.” “I underestimated the situation.” Mohsin looked over his shoulder. “He is actually close.” Mohsina folded her arms. “That does not make it his turn.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 100040),
          end: Duration(milliseconds: 120147),
          text:
              'Akhlaq finally completed the level, cheered, and immediately began the next one. Mohsina stared at him. “What are you doing?” “Saving my progress.” “That does not look like saving.” “It is a complicated game.” “Akhlaq.” He sighed. “Just five more minutes.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 120742),
          end: Duration(milliseconds: 143075),
          text:
              'Mohsina looked towards the clock. “You have already taken seven extra.” Akhlaq replied that it was only a few minutes. Imaan noticed how familiar the sentence sounded. “Yesterday it was ‘only a little water.’” Akhlaq ignored her and continued playing. By the time he finally handed the tablet over, he had used almost twelve extra minutes.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 143852),
          end: Duration(milliseconds: 168451),
          text:
              'Mohsina took it but did not smile. Akhlaq asked what was wrong. She explained that he had used part of her turn. Akhlaq said he had only used twelve minutes and that she still had plenty of time. Mohsina reminded him that dinner preparation would start earlier because guests were coming. Akhlaq shrugged and told her to use it quickly.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 169143),
          end: Duration(milliseconds: 190337),
          text:
              'Mohsina looked at him. “That is not the point.” Akhlaq was genuinely confused. “I didn’t break it. I didn’t stop you using it. I only kept it a little longer.” Mohsina replied quietly, “Those twelve minutes were not extra minutes.” She held up the tablet. “They were mine.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 190337),
          end: Duration(milliseconds: 211967),
          text:
              'The room became silent. Even Akhlaq stopped smiling. Mohsin tried to ease the tension by offering Mohsina twelve minutes from his own turn. She shook her head. “That is kind, but then you lose twelve minutes because Akhlaq took mine. Why should your turn fix his choice?” Mohsin had no answer.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 212257),
          end: Duration(milliseconds: 235955),
          text:
              'Ammi had been preparing tea in the kitchen and heard the conversation. She came into the room and asked Akhlaq whether he knew when his turn ended. He said yes. She asked whether Mohsina had agreed to give him part of hers. He said no. Then she asked what exactly he had taken. Akhlaq looked uncomfortable. “Time.” “Whose time?” He sighed. “Mohsina’s.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 238100),
          end: Duration(milliseconds: 259923),
          text:
              'Ammi nodded. She explained that this was why learning about rights mattered. Sometimes people imagined they were taking something that belonged to nobody simply because it was sitting there. Imaan remembered the previous day’s lesson. “Like the reserve water looked like extra water until we knew what it was for.” Ammi smiled. “Exactly.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 260461),
          end: Duration(milliseconds: 274451),
          text:
              'Akhlaq turned to Mohsina and apologised. He offered to give her twelve minutes from his next turn, and she accepted. Mohsin looked disappointed that his generosity had been rejected, and everyone laughed, softening the tension.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 274451),
          end: Duration(milliseconds: 297579),
          text:
              'That afternoon, Abbu found the four children sitting in the family room. Akhlaq told him what had happened before anyone else could. “I stole twelve minutes.” Abbu raised an eyebrow and said that sounded dramatic. Mohsina clarified that he had used twelve minutes of her turn without asking. Abbu said that sounded more accurate.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 297839),
          end: Duration(milliseconds: 317267),
          text:
              'Abbu reminded them that Allah had given the people of Thamud a clear sign: the she-camel. Salih (A.S.) told his people not to harm her. The Qur’an also tells us that there was an appointed sharing of water. “The she-camel had a share,” Abbu explained, “and the people had their share on an appointed day.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 318881),
          end: Duration(milliseconds: 332355),
          text:
              'Mohsin frowned slightly. “So they could not just use the water whenever they wanted?” Abbu said they had to respect the arrangement Allah had given. Akhlaq looked towards the tablet and said he saw where this was going.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 332964),
          end: Duration(milliseconds: 348603),
          text:
              'Mohsina asked whether the problem was only about water. Abbu replied that the lesson was larger. The water arrangement showed that another right existed alongside their own. They were not allowed to behave as though only their needs mattered.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 349033),
          end: Duration(milliseconds: 357723),
          text:
              'Imaan said, “So if something is shared fairly, my right does not erase somebody else’s.” Abbu agreed.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 358030),
          end: Duration(milliseconds: 393219),
          text:
              'Abbu asked them to imagine four glasses of juice on a tray, one for each child. If Akhlaq drank his own and then half of Mohsin’s while Mohsin was outside, he could not say, “There was still juice on the table.” The second glass was Mohsin’s. If Akhlaq was still thirsty, he should ask. If the tablet sat unused while Mohsina fetched water during her turn, it was still her turn. If Dadi Jaan left her favourite chair for two minutes, the children should ask before taking it if they knew she was coming back.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 393729),
          end: Duration(milliseconds: 401459),
          text:
              'Mohsin said, “Something can be available but not available to me.” Abbu called that an excellent way to put it.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 401459),
          end: Duration(milliseconds: 436515),
          text:
              'The children grew thoughtful. For Akhlaq, the lesson was particularly uncomfortable because he liked things to be practical. If nobody was using something at that exact moment, it felt wasteful to leave it alone. But now he realised that respecting a right sometimes meant respecting something that could not be seen: a turn, a promise, a reservation, someone’s privacy, someone’s portion or someone’s time. The absence of the person did not make the right disappear.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 436515),
          end: Duration(milliseconds: 471811),
          text:
              'Later, Dadi Jaan joined them with a bowl of sliced mangoes. She placed the bowl on the table and said, “One portion each.” Akhlaq immediately looked at everyone. “Why is everyone looking at me?” “No reason,” Imaan replied. He carefully took his portion. When Mohsin left the room to answer a call from his mother, one piece of mango remained on his plate. Akhlaq stared at it. Mohsina noticed. “Available?” Akhlaq looked at her. “Not to me.” Dadi Jaan laughed. “Progress.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 485299),
          end: Duration(milliseconds: 503319),
          text:
              'That evening, Abbu asked why respecting turns was difficult. Mohsin said sometimes he wanted something now. Imaan added that waiting felt unnecessary when the thing was right in front of her. Mohsina said people often thought their own need was more important because they could feel it more strongly. Abbu nodded. They naturally felt their own hunger, boredom, excitement or impatience more strongly than another person’s need.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 503781),
          end: Duration(milliseconds: 521827),
          text:
              'Akhlaq looked at Mohsina. When he had wanted five more minutes, he could feel how much he wanted to finish the level, but he could not feel what losing twelve minutes meant to her. Abbu agreed and explained that justice often required remembering rights one could not personally feel.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 523187),
          end: Duration(milliseconds: 539755),
          text:
              'The people of Thamud had been given a clear boundary concerning the she-camel. Her appointed share was not theirs to take merely because they wanted it. “Another person’s right does not become smaller because your desire becomes bigger,” Abbu said.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 540228),
          end: Duration(milliseconds: 570291),
          text:
              'Mohsin then asked what happened when the people became tired of the arrangement. Abbu’s expression changed. Their rejection eventually became deliberate. Mohsina asked whether it was everyone. Abbu explained that the Qur’an shows the wrongdoing reached a point where the she-camel was harmed and the people were held responsible for their rebellion. He said they would talk more carefully about individual and group responsibility the next day.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 571011),
          end: Duration(milliseconds: 585091),
          text:
              'Mohsin looked uneasy. “Why tomorrow?” Abbu answered, “Because tomorrow’s lesson is about a dangerous sentence.” “What sentence?” Abbu looked at all four children. “Everyone is doing it.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 585139),
          end: Duration(milliseconds: 621587),
          text:
              'Just then, Mohsin looked through the window towards the garden hose. The afternoon had been hot again. He remembered how much fun the water game would have been. Then he looked at the refrigerator chart: DO NOT USE THE RESERVE WATER. He understood the rule now. He knew why the water was being saved. And that meant that if he crossed the boundary tomorrow, he would no longer be able to say he had not understood. The next test would not be about knowledge. It would be about choice.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 621587),
          end: Duration(milliseconds: 625789),
          text: 'Challenge of the Day: Respect Someone Else’s Share',
        ),
        CaptionLine(
          start: Duration(milliseconds: 625789),
          end: Duration(milliseconds: 637061),
          text:
              'Today, notice one shared thing: food, screen time, a toy, a seat, space, money, equipment or someone’s time.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 637061),
          end: Duration(milliseconds: 644515),
          text:
              'Before taking more, ask: “Am I using my share, or am I beginning to use someone else’s?”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 645043),
          end: Duration(milliseconds: 645646),
          text: 'Level-Up',
        ),
        CaptionLine(
          start: Duration(milliseconds: 646334),
          end: Duration(milliseconds: 651843),
          text:
              'Practise waiting for one turn today without complaining or trying to extend your time.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 652343),
          end: Duration(milliseconds: 658743),
          text:
              'Something may be available in front of you and still belong to someone else’s right.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 659243),
          end: Duration(milliseconds: 662665),
          text: 'Next Episode: Ammi Will Never Know',
        ),
      ],
    ),
    Story(
      id: 'salih_en_04',
      title: 'Ep 4 · Ammi Will Never Know',
      narrator: 'Imaan & Akhlaq',
      coverAsset: 'assets/covers/salih.webp',
      audioAsset: 'assets/audio/en/salih/04_ammi_will_never_know.ogg',
      category: StoryCategory.prophets,
      description: 'Hazrat Salih (A.S.) — episode 4 of 5.',
      captions: [
        CaptionLine(
          start: Duration(milliseconds: 378),
          end: Duration(milliseconds: 2578),
          text: 'Episode 4: Ammi Will Never Know',
        ),
        CaptionLine(
          start: Duration(milliseconds: 22634),
          end: Duration(milliseconds: 23434),
          text:
              'The afternoon heat had settled over the house like a heavy blanket. Mohsin lay beneath the fan, Akhlaq sat beside the window, and Imaan and Mohsina were finishing a puzzle. Ammi and Abbu were busy downstairs because relatives were expected for tea, while Dadi Jaan was resting.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 23434),
          end: Duration(milliseconds: 44680),
          text:
              'Through the window they could see the garden hose curled beside the wall. Mohsin sat up. “What if we just wet the ground a little?” Imaan did not look up. “No.” “I did not say water fight.” “You were thinking water fight.” Mohsina pointed downstairs. “The rule can hear you.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 44680),
          end: Duration(milliseconds: 73530),
          text:
              'They all knew the rule now. Abbu had shown them the tank, the reserve line and the amount the family might need if the next water supply was delayed. There was no confusion left. Akhlaq looked outside. “The tanker is supposed to come tomorrow.” “Supposed to,” Imaan replied. Mohsin smiled. “Exactly. So all this reserve will just be replaced.” Mohsina frowned. “That does not make it ours to waste today.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 74330),
          end: Duration(milliseconds: 103758),
          text:
              'For several minutes nobody spoke. Then laughter came from the kitchen. The adults were busy, and the house felt unusually unsupervised. Mohsin lowered his voice. “Five minutes.” “No,” Imaan said. “Two?” “No.” “One?” “A rule does not change because you bargain with it.” Akhlaq laughed. “That sounded like Ammi.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 105546),
          end: Duration(milliseconds: 123154),
          text:
              'Then Mohsin said the sentence that changed the mood. “Nobody would even know.” Imaan looked at him. “That makes it worse.” “Why?” “Because now you are not asking whether it is right. You are asking whether you can hide it.” Mohsin had no answer.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 123154),
          end: Duration(milliseconds: 144295),
          text:
              'Akhlaq knew she was right, but the cold water still sounded tempting. The reserve line felt far away inside a tank above the roof. The hose was right outside. Mohsin stood. “Fine. I am going.” Imaan and Mohsina refused to join. Akhlaq hesitated for a few seconds. Then he followed.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 144295),
          end: Duration(milliseconds: 167490),
          text:
              'Outside, Mohsin opened the tap slightly. Water rushed into the hose. “See?” he whispered. “Hardly anything.” He sprayed the ground, then Akhlaq’s shoes. Akhlaq laughed and grabbed the hose. Within seconds, “one minute” became chasing each other around the garden. They tried to keep the water low, but excitement made them forget.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 167818),
          end: Duration(milliseconds: 186618),
          text:
              'Imaan appeared at the doorway. “Stop.” Mohsin lowered the hose. “You are going to get us caught,” he said. Imaan stared at him. “That is what worries you?” Mohsina pointed towards the garden clock. Nearly nine minutes had passed. Akhlaq’s smile disappeared. Mohsin closed the tap.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 186618),
          end: Duration(milliseconds: 215226),
          text:
              '“It is done now,” Akhlaq said. “That does not make it fine,” Imaan replied. “We cannot put the water back.” “No,” Mohsina said, “but you can stop pretending it was nothing.” Mohsin picked up the hose. “The tanker is coming tomorrow.” “You do not know that,” Imaan said. “It usually comes.” “That is not the same thing.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 215812),
          end: Duration(milliseconds: 226205),
          text:
              'Akhlaq felt irritated because he knew she was right. “Nothing has happened.” Mohsina looked at him carefully. “Nothing has happened yet.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 226205),
          end: Duration(milliseconds: 247682),
          text:
              'That evening, the children said nothing. The visitors came, everyone had tea, and no tap stopped working. Before leaving, Mohsin whispered to Akhlaq, “See? We worried too much.” Akhlaq wanted to agree, but the sentence did not feel comforting.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 247682),
          end: Duration(milliseconds: 271510),
          text:
              'The next morning, Ammi turned on the kitchen tap. The water came weakly, then stopped. She tried again. Nothing. Abbu checked the tank and returned looking serious but calm. “The level has fallen below where it should be. We will have to be very careful until the tanker comes.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 272268),
          end: Duration(milliseconds: 291628),
          text:
              'Dadi Jaan entered and asked for water to take her medicine. Ammi immediately brought drinking water from the covered container kept separately, but the sight of Dadi Jaan made yesterday’s game suddenly feel much larger. Mohsin had arrived early. He looked at Akhlaq. Neither spoke.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 291941),
          end: Duration(milliseconds: 310586),
          text:
              'Abbu noticed. “Is there something you need to tell us?” Akhlaq’s first thought was that perhaps the water level had dropped for other reasons. Then he remembered the lesson about another person’s share. Mohsin spoke first. “We used the garden hose yesterday.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 310586),
          end: Duration(milliseconds: 339754),
          text:
              'The kitchen became silent. Ammi looked at them. “After Abbu showed you why the water was reserved?” Mohsin nodded. She asked how long. Akhlaq answered quietly that they had meant one or two minutes, but it had become nearly nine. Abbu asked who opened the tap. “I did,” Mohsin said. Akhlaq immediately added, “I joined him.” Imaan and Mohsina explained that they had refused.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 341124),
          end: Duration(milliseconds: 367050),
          text:
              'Abbu asked why they did it. Mohsin said it was hot. Akhlaq said they thought the tanker would come that day. Then Mohsin admitted, “We thought nobody would know.” Abbu was quiet for a moment. “That may be the most important part. When you begin asking, ‘Will anyone know?’ instead of ‘Is this right?’ you are already moving in a dangerous direction.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 368050),
          end: Duration(milliseconds: 392871),
          text:
              'Later, once the family had arranged its immediate water needs, Abbu gathered the four children in the sitting room. He reminded them of Salih (A.S.) and Thamud. They had received a clear sign and a clear boundary concerning the she-camel. Yet the Qur’an tells us that the she-camel was deliberately harmed.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 393352),
          end: Duration(milliseconds: 412986),
          text:
              'Mohsin asked quietly whether it was one person. Abbu answered carefully. The Qur’an describes one man who undertook the act, while other verses speak of the people collectively in their rejection and rebellion. That teaches something about group responsibility.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 413645),
          end: Duration(milliseconds: 440474),
          text:
              'Akhlaq asked whether, if one person actually did something, others could still share responsibility. Abbu explained that if they encouraged it, supported it, approved it or willingly joined the wrongdoing, they could share in blame for their own part. But every person is accountable before Allah for their own choices, and they should not accuse someone of what they did not do.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 441058),
          end: Duration(milliseconds: 458442),
          text:
              'Mohsina asked what happened if someone knew it was wrong but was scared to speak. Abbu said that could be a different situation; Allah knows each person’s circumstances and ability. But “everyone wanted it” was never an excuse for a choice willingly made.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 458961),
          end: Duration(milliseconds: 478610),
          text:
              'Mohsin looked uncomfortable. “I kept saying everyone wanted the water game.” Imaan reminded him that they did not. “I know.” “And even if we had?” Mohsin sighed. “I still opened the tap myself.” Abbu nodded. Akhlaq added, “And I chose to follow him.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 478860),
          end: Duration(milliseconds: 506266),
          text:
              'Abbu explained that wrongdoing often began with sentences that made it sound smaller: “Only once.” “Only a little.” “Nobody will know.” “Everyone agrees.” “Nothing happened last time.” Akhlaq looked towards the kitchen. “Nothing happened yesterday.” “And that fooled you,” Abbu replied. Mohsina remembered her warning. “The consequence was delayed, not absent.” “Exactly.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 506498),
          end: Duration(milliseconds: 524514),
          text:
              'Abbu then made an important distinction. Their water shortage was an ordinary consequence of wasting a limited resource. It was not the punishment that came upon Thamud. They were learning from the story about knowingly crossing a clear boundary, not saying the two events were equal.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 526514),
          end: Duration(milliseconds: 559615),
          text:
              'Ammi asked the boys what accountability should look like. Akhlaq suggested they should help with whatever extra work their mistake had caused. Mohsin agreed. They helped carry safe stored water for cleaning under adult supervision, avoided unnecessary use and gave up the idea of any water games until the supply became stable again. Abbu also asked them to check the water level with him later so they could see how slowly a limited reserve returned once it had been wasted.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 559615),
          end: Duration(milliseconds: 565450),
          text:
              'Nobody shouted at them. But neither did anyone pretend the choice had been harmless.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 567450),
          end: Duration(milliseconds: 595418),
          text:
              'Before lunch, Akhlaq stopped in front of the refrigerator chart. The same line was still there: DO NOT USE THE RESERVE WATER. Yesterday, he had understood it. Then he had crossed it anyway. Mohsin came beside him. “I kept thinking, ‘Everyone wants to do it.’” Akhlaq looked at him. “There were only two of us.” Mohsin laughed weakly. “That makes it worse.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 596378),
          end: Duration(milliseconds: 619066),
          text:
              'Then Mohsin became serious. “I think I wanted the group to carry my decision for me.” Akhlaq nodded. “But groups do not make choices for us.” Mohsina, standing behind them, added, “They can influence us.” Imaan finished the thought. “But we still answer for what we choose.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 619602),
          end: Duration(milliseconds: 641314),
          text:
              'Akhlaq looked again at the rule. Sometimes the hardest boundary to respect was not the one you did not understand. It was the one you understood perfectly but wanted to cross because somebody beside you made disobedience feel normal. And that was why the story of Salih (A.S.) was becoming more serious.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 641314),
          end: Duration(milliseconds: 646070),
          text: 'Challenge of the Day: Do Not Hide Behind the Group',
        ),
        CaptionLine(
          start: Duration(milliseconds: 646070),
          end: Duration(milliseconds: 660339),
          text:
              'Today, notice one moment when someone says: “Everyone is doing it.” Before joining, ask: “If I were the only person making this choice, would I still think it was right?”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 660339),
          end: Duration(milliseconds: 661290),
          text: 'Level-Up',
        ),
        CaptionLine(
          start: Duration(milliseconds: 661290),
          end: Duration(milliseconds: 675090),
          text:
              'Watch for these excuses: “Only once.” “Only a little.” “Nobody will know.” “Everyone agrees.” If you hear yourself using one of them, stop and reconsider.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 675090),
          end: Duration(milliseconds: 681258),
          text:
              'Other people can influence your choice. They cannot carry your responsibility for you.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 681258),
          end: Duration(milliseconds: 685499),
          text: 'Next Episode: The Rule Was Not the Enemy',
        ),
      ],
    ),
    Story(
      id: 'salih_en_05',
      title: 'Ep 5 · The Rule Was Not the Enemy',
      narrator: 'Imaan & Akhlaq',
      coverAsset: 'assets/covers/salih.webp',
      audioAsset: 'assets/audio/en/salih/05_the_rule_was_not_the_enemy.ogg',
      category: StoryCategory.prophets,
      description: 'Hazrat Salih (A.S.) — episode 5 of 5.',
      captions: [
        CaptionLine(
          start: Duration(milliseconds: 139),
          end: Duration(milliseconds: 4919),
          text: 'Episode 5: The Rule Was Not the Enemy',
        ),
        CaptionLine(
          start: Duration(milliseconds: 4919),
          end: Duration(milliseconds: 27727),
          text:
              'The morning after the water shortage felt different from every other holiday morning. No one complained when Ammi reminded them to use water carefully. Akhlaq brushed his teeth without leaving the tap running. Mohsin helped Abbu carry a small container of stored water to the kitchen. Even the usual argument over who would wash the breakfast dishes disappeared.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 28394),
          end: Duration(milliseconds: 55535),
          text:
              'Akhlaq noticed it first. “Yesterday this house had too many rules,” he said quietly. Mohsina looked at him. “And today?” “Today I am measuring how much water I use to rinse a plate.” Mohsin sighed. “Consequences are very educational.” Imaan smiled. “Especially when the lesson was already explained before the consequence.” Mohsin gave her a look. “Thank you for that.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 55663),
          end: Duration(milliseconds: 77711),
          text:
              'The tanker still had not arrived. The family had enough drinking water stored safely, but everything else had to be carefully managed. Ammi used one basin for washing vegetables and another for dishes. Abbu postponed washing the car. The children helped collect water that could safely be reused for the outdoor plants.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 77711),
          end: Duration(milliseconds: 94991),
          text:
              'Nobody treated the situation like a disaster. It was inconvenient, but manageable. That somehow made Akhlaq feel more responsible. He had expected anger. Instead, he was seeing how one careless choice created extra work for everyone.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 95886),
          end: Duration(milliseconds: 123847),
          text:
              'Dadi Jaan entered the kitchen carrying her empty cup and asked if someone could fill it. Akhlaq immediately stood and brought her drinking water. Dadi Jaan smiled and thanked him. Mohsin whispered, “Yesterday you were spraying water at my shoes.” Akhlaq replied, “I remember.” Mohsin looked at the cup. “That cup suddenly looks important.” “It is important.” The boys exchanged a glance. Neither needed to say more.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 123847),
          end: Duration(milliseconds: 148255),
          text:
              'Later that morning, Abbu called all four children into the sitting room. On the table was the holiday chart that had previously been attached to the refrigerator. Akhlaq looked at it suspiciously and asked whether they were receiving additional rules. Abbu said no. He wanted them to tell him what one particular rule had been trying to protect: DO NOT USE THE RESERVE WATER FOR GAMES.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 148688),
          end: Duration(milliseconds: 166503),
          text:
              'Imaan answered first: the family’s basic needs. Mohsina added: water if the next supply was delayed. Mohsin looked towards Dadi Jaan’s room and said: people who might need it more than their game. Akhlaq thought for a moment. “Tomorrow.” Everyone looked at him.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 166803),
          end: Duration(milliseconds: 177471),
          text:
              'Abbu asked him to explain. Akhlaq said, “The rule was protecting tomorrow from what we wanted today.” Abbu nodded. “That is an important lesson.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 178720),
          end: Duration(milliseconds: 216407),
          text:
              'Akhlaq looked at the paper. The rule had felt like the problem because it was standing between them and what they wanted. But the rule had actually been a warning that there was something they could not see yet. Abbu reminded them that not every rule adults make is automatically perfect. Parents and teachers can make mistakes and children may respectfully ask questions. But a reasonable boundary that protects health, safety, another person’s right or an important responsibility is not an enemy simply because it prevents immediate enjoyment.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 216924),
          end: Duration(milliseconds: 226847),
          text:
              'Mohsin sat forward. “Is this where we finish the story of Salih (A.S.)?” Abbu said yes. The children became attentive.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 227128),
          end: Duration(milliseconds: 253615),
          text:
              'Abbu reminded them that Allah had sent Salih (A.S.) to Thamud. He called his people to worship Allah alone. Allah had given them great abilities and blessings, and they had received the she-camel as a clear sign. They were given clear instructions concerning her and warned not to harm her. But the Qur’an tells us that they deliberately harmed the she-camel despite the warning.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 254038),
          end: Duration(milliseconds: 272563),
          text:
              'Akhlaq looked uncomfortable and asked what happened after that. Abbu explained that Salih (A.S.) gave them a clear warning. The Qur’an tells us that after their crime they were told to enjoy themselves in their homes for three days, and that the warning was not false.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 273099),
          end: Duration(milliseconds: 287151),
          text:
              'Mohsina asked whether they still had time to understand what they had done. Abbu replied that they had already been given the message, the sign and the warning. The seriousness was now unmistakable.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 287615),
          end: Duration(milliseconds: 323247),
          text:
              'Mohsin lowered his voice and asked what happened after the three days. Abbu kept his answer simple. Allah’s punishment came upon those who persisted in rejection and wrongdoing. The Qur’an describes the punishment of Thamud in different passages with powerful words, including a mighty blast and an earthquake. They did not need to make the scene frightening with invented details. What mattered was that the people who believed their boundary could be ignored discovered that Allah’s warning was true.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 323680),
          end: Duration(milliseconds: 341215),
          text:
              'Imaan asked what happened to Salih (A.S.). Abbu answered that Allah saved Salih (A.S.) and those who believed with him by His mercy. Akhlaq remembered Hud’s story. “Again, by Allah’s mercy.” Abbu agreed.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 342523),
          end: Duration(milliseconds: 374303),
          text:
              'Then Abbu made something very clear. What happened in their home was not a smaller version of the punishment of Thamud. They had wasted limited household water and experienced an ordinary consequence. Thamud knowingly rejected a Prophet of Allah and violated a divine sign. These were not equal events. They were learning from the principle: what can happen when a person becomes so determined to cross a clear boundary that the boundary itself starts to feel like the enemy.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 375653),
          end: Duration(milliseconds: 389471),
          text:
              'Mohsin looked thoughtful. Yesterday he had kept thinking Abbu’s rule was stopping their fun. In reality, the rule was protecting water. When the water became low, its wisdom became more visible.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 389960),
          end: Duration(milliseconds: 420087),
          text:
              'Akhlaq asked what happened if he never understood the wisdom of a rule. Abbu explained that for Allah’s commands, a believer obeys Allah even when they do not fully understand every wisdom behind the command. With human rules, children may respectfully ask, discuss and seek clarification. But at home, if parents give a reasonable, safe instruction within their responsibility, not understanding everything immediately does not mean the child should secretly ignore it.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 420907),
          end: Duration(milliseconds: 431967),
          text:
              'Akhlaq nodded. That felt balanced. Not: Never ask. Not: Adults are always right. But also not: I obey only when I personally agree.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 435632),
          end: Duration(milliseconds: 454975),
          text:
              'That afternoon, the tanker finally arrived. Mohsin heard the sound from outside and ran towards the window. “Water!” Akhlaq joined him. For a moment, they celebrated as though a major national crisis had ended. Ammi laughed from the kitchen and told them to remember that enthusiasm the next time they wanted a water fight.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 455023),
          end: Duration(milliseconds: 481231),
          text:
              'As the tank refilled, Abbu took the children upstairs again. They watched the level slowly rise. Akhlaq pointed towards the reserve mark and said they should repaint it because part of it had faded. Abbu handed him the paint. All four children helped. Imaan held the small container, Mohsina cleaned the surface, Mohsin helped measure the correct position, and Akhlaq carefully painted the line again.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 481231),
          end: Duration(milliseconds: 497268),
          text:
              'He made it thicker than before. Mohsin laughed and asked why it was so big. Akhlaq stepped back and examined it. “So nobody can pretend they didn’t see it.” Everyone laughed. But then Akhlaq added more seriously, “Including me.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 497268),
          end: Duration(milliseconds: 514719),
          text:
              'That evening, they made one final change to the holiday chart. Ammi had originally written OUR HOLIDAY HOME PLAN. Akhlaq asked whether they could change the heading. After discussing it together, they wrote: HOW WE TAKE CARE OF EACH OTHER AT HOME.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 514927),
          end: Duration(milliseconds: 540335),
          text:
              'The rules underneath remained almost the same. Screen time still had limits. Shared things still required fair turns. Dadi Jaan still had quiet time. The children still had to tell an adult before leaving. And reserve water was still not for games. But the chart looked different now. Not because the words had changed very much. Because the children had.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 540798),
          end: Duration(milliseconds: 573543),
          text:
              'Akhlaq stood in front of it for a long moment and asked Abbu whether he would still say no to them during the holidays. Abbu smiled. “Many times.” Akhlaq sighed dramatically. Abbu added that whenever he reasonably could, he would explain why. Akhlaq asked what happened if he still did not like the answer. Ammi smiled and said he was allowed not to like every boundary. Dadi Jaan added, “That is one of the privileges of being human.” Everyone laughed.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 573726),
          end: Duration(milliseconds: 602304),
          text:
              'Abbu finished the thought. “But learning to respect a reasonable boundary even when you dislike it is part of becoming responsible.” Mohsin looked towards the new chart and said that if everyone else wanted to break it, he still had to make his own choice. Mohsina added that someone else’s right did not disappear because he wanted more. Akhlaq pointed towards the title and said maybe the rule was not always trying to control him.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 602620),
          end: Duration(milliseconds: 610888),
          text:
              'Abbu asked what it might be doing instead. Akhlaq smiled. “Taking care of something I have not noticed yet.”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 610888),
          end: Duration(milliseconds: 629607),
          text:
              'The story of Salih (A.S.) had begun for them with one complaint: Why is everything a rule? It ended with a very different question: What is this boundary protecting? And sometimes, that question made all the difference.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 629607),
          end: Duration(milliseconds: 633972),
          text: 'Challenge of the Day: Find What the Boundary Protects',
        ),
        CaptionLine(
          start: Duration(milliseconds: 633972),
          end: Duration(milliseconds: 646755),
          text:
              'Choose one reasonable rule at home that sometimes annoys you. Ask yourself: “What person, right, responsibility or future consequence might this rule be protecting?”',
        ),
        CaptionLine(
          start: Duration(milliseconds: 646755),
          end: Duration(milliseconds: 651415),
          text:
              'Try to respect it today without needing someone to remind you.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 651415),
          end: Duration(milliseconds: 653175),
          text: 'Level-Up',
        ),
        CaptionLine(
          start: Duration(milliseconds: 653175),
          end: Duration(milliseconds: 663823),
          text:
              'When you disagree with a family boundary, practise three steps: Ask respectfully. Listen carefully. Respond responsibly.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 663823),
          end: Duration(milliseconds: 673290),
          text:
              'A boundary can feel like an obstacle when we only see what it stops. Wisdom begins when we also see what it protects.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 673290),
          end: Duration(milliseconds: 674671),
          text: 'End of Hazrat Salih (A.S.) Series',
        ),
        CaptionLine(
          start: Duration(milliseconds: 674671),
          end: Duration(milliseconds: 678671),
          text: 'The five lessons of the journey:',
        ),
        CaptionLine(
          start: Duration(milliseconds: 678671),
          end: Duration(milliseconds: 687511),
          text:
              'Episode 1 — Why Is Everything a Rule? Being able to do something does not always mean having the right to do it.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 687511),
          end: Duration(milliseconds: 694631),
          text:
              'Episode 2 — But Tell Me Why. Respectful questions seek understanding, but understanding brings responsibility.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 696639),
          end: Duration(milliseconds: 704199),
          text:
              'Episode 3 — That Was My Turn. Someone else’s share remains their right even when you want it.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 704199),
          end: Duration(milliseconds: 712919),
          text:
              'Episode 4 — Ammi Will Never Know. The group can influence your choice, but it cannot carry your responsibility.',
        ),
        CaptionLine(
          start: Duration(milliseconds: 712919),
          end: Duration(milliseconds: 720367),
          text:
              'Episode 5 — The Rule Was Not the Enemy. A reasonable boundary may be protecting something you cannot yet see.',
        ),
      ],
    ),
  ],
);
