// Turns tools/challenges.json into lib/models/challenges.dart, the map the
// Parents area reads.
//
//   node tools/gen_challenges_dart.mjs
//
// Run tools/extract_challenges.mjs first: it is what builds challenges.json
// out of the narration scripts and tools/challenges.written.json.
//
// The catalogue is compiled in rather than loaded at runtime, the same way
// lib/models/series/*.dart are, so a missing challenge is a compile error
// instead of a blank card on somebody's phone.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repo = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(repo, 'lib', 'models', 'challenges.dart');

const challenges = JSON.parse(
  readFileSync(join(repo, 'tools', 'challenges.json'), 'utf8'),
);

// Episode ids live in the generated web catalogue, which is built from the
// same series files the app uses, so the two cannot drift.
const series = JSON.parse(
  readFileSync(join(repo, 'site', 'src', 'data', 'stories.generated.ts'), 'utf8')
    .replace(/^[\s\S]*?= \[/, '[').trimEnd().replace(/;$/, ''),
);

/** `it's` -> `it\'s`, and Dart interpolates `$` unless it is escaped. */
const dart = (s) => `'${String(s ?? '')
  .replace(/\\/g, '\\\\')
  .replace(/'/g, "\\'")
  .replace(/\$/g, '\\$')
  .replace(/\r?\n/g, ' ')
  .trim()}'`;

const entries = [];
let written = 0, missing = [];

for (const s of series) {
  const list = challenges[s.id] ?? [];
  s.episodes.forEach((episode, i) => {
    const c = list[i];
    if (!c) {
      missing.push(episode.id);
      return;
    }
    if (c.written) written++;
    entries.push(
      `  ${dart(episode.id)}: Challenge(\n` +
      `    title: ${dart(c.title)},\n` +
      `    mission: ${dart(c.mission)},\n` +
      (c.reflection ? `    reflection: ${dart(c.reflection)},\n` : '') +
      (c.levelUp ? `    levelUp: ${dart(c.levelUp)},\n` : '') +
      `  ),`,
    );
  });
}

const out = `// GENERATED by tools/gen_challenges_dart.mjs from tools/challenges.json.
// Do not edit by hand: change the narration script, or
// tools/challenges.written.json, and rerun.
//
// The challenge each episode closes on, keyed by story id. Most were lifted
// out of the narration scripts; the rest were written for episodes whose
// script never had one.

import 'challenge.dart';

const Map<String, Challenge> challengesByStoryId = {
${entries.join('\n')}
};
`;

writeFileSync(OUT, out);
console.log(`wrote ${entries.length} challenges (${written} hand-written) -> ${OUT}`);
if (missing.length) {
  console.log(`\n${missing.length} episodes still without one:`);
  missing.forEach((id) => console.log('  ' + id));
}
